### ISSUE TITLE
Releases Downloads

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#1005]
On this page https://www.boost.io/releases/ the downloads are currently originating from https://boostorg.jfrog.io.    Switch to archives.boost.io instead.  

Today is 2024-03-05, since the download is new let's wait a week, in the absence of any reported problems, just go ahead after 2024-03-12.

**Comment by sdarwin** [comment]
Hi @williln , if you have a chance, this one is sort of a priority.  Modify download links to archives.boost.io 

(The new path does not include /artifactory/main/)

**Comment by 4down** [comment]
@sdarwin Are we no longer going to be able to call the API at boostorg.jfrog.io, or can that part of the process remain intact and then we can simply do a replace on the domain name after we get the URLs?  

Right now we call the API to get the download URLs, so it will affect how we handle things if that API will no longer be accessible to us.

**Comment by sdarwin** [comment]
boostorg.jfrog.io was a donation provided to boost by jfrog, and it's scheduled to end this year.  The API will cease to be available.   

The naming scheme for downloads is generally consistent and repeatable, especially for standard releases, and could be "predicted" or "guessed" based on a standard pattern:  
 
https://archives.boost.io/release/1.84.0/source/boost_1_84_0.tar.bz2
 
Another idea is to parse the html source code of index pages such as: https://archives.boost.io/release/1.84.0/source/ , and check which downloads (if any) have been published there.
