### ISSUE TITLE
Clicking on library docs links shows redirection page briefly

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#1009]
Problem:
The unordered docs show "redirection failed" when clicking on them.

Explanation:
`libs/unordered/index.html` is an html redirect `doc/libs/1_84_0/libs/unordered/doc/html/unordered.html`. Since the unordered page is huge, multiple MBs, it takes time to load. After a minute, a refresh will be served by the CDN, and faster, but it still takes time even then. Either way, during the interval the webpage appears to say "redirection failed" while waiting.

Solution:
One idea, since `libs/unordered/index.html` is a field in the boost.io database, add more logic during the db import step when the field is populated, to ascertain that the "real" answer should be `doc/libs/1_84_0/libs/unordered/doc/html/unordered.html` instead of `libs/unordered/index.html`, by either actually following redirect, or by parsing the source code of `libs/unordered/index.html`.

**Comment by kennethreitz** [comment]
I wish more of the projects did a homepage like this: https://www.stage.boost.cppalliance.org/doc/libs/boost_1_84_0/libs/rational/index.html

Are the JS redirects all setup via the authors of the libraries?

**Comment by sdarwin** [comment]
The meta redirect is per library. However, almost none of them are set up like Boost.Rational.
`<meta http-equiv="refresh" content="0; URL=doc/html/unordered.html">`

**Comment by kennethreitz** [comment]
This should be resolved on staging now, thanks to #1029!
