### ISSUE TITLE
Library categories "Containers" and "Container"

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1034]
There are two categories "Containers" and "Container", the latter holding only Static String. I'd suggest that these two categories be merged into a single "Containers".

**Comment by joaquintides** [comment]
Does this mean that the categories in boost.org are hard-coded and not retrieved from meta/libraries.jsons? Interesting

**Comment by kennethreitz** [comment]
I need to look into it further to be able to answer that question :)

**Comment by rbbeeston** [comment]
@vinniefalco and/or @joaquintides - should this get merged?

**Comment by vinniefalco** [comment]
There is no pull request here. Should the StaticString PR get merged? Maybe. It can't hurt.

However I think we need something more heavy duty. The database should keep track of the current categories per-version. And there should be an "aliases" table which lets "Container" and "Containers" map to the same category. There might already be an issue for the per-version categories calculation. Sam had a lot of replies on how it should be done in that issue, which I disagreed with.

**Comment by vinniefalco** [comment]
Here: https://github.com/boostorg/website-v2/issues/1224

**Comment by joaquintides** [comment]
As a quick (and ultimate necessary) fix, a PR to StaticString changing "Container" to "Containers" here would do:

https://github.com/boostorg/static_string/blob/develop/meta/libraries.json

**Comment by vinniefalco** [comment]
@joaquintides that fixes it in the current branches but if you go back to older releases then the category will revert. We need the system for dynamic calculation of categories, with a manual table for mapping aliases.

**Comment by rbbeeston** [comment]
in that case, as it's a minor issue, we should fix it all in one go. Leaving it open, and moving to accepted. marking as an "Under the hood" task

**Comment by sdarwin** [comment]
A "table for mapping aliases" may go directly in the django code, rather that the database.  
Something similar has been done to fix many exceptions from old libraries with unusual doc paths or categories. 
A series of mappings or aliases.  
Also for the isomap, to redirect url links.

**Comment by GregKaleka** [comment]
I'm going to follow @sdarwin's suggestion of hard-coding the mapping since it does feel similar to the other examples he mentions above. If anyone feels strongly this should be more dynamic and we need some form of canonical category mapping management in the admin, please chime in (soon).
