### ISSUE TITLE
Anonymous users should not set Cookies

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#1039]
To investigate:  
An idea with the CDN is 90% of visitors will probably not log in.  Most visitors are anonymous users.   That makes CDN caching easier, since they won't have browser cookies set, and therefore the same html content can be served to everyone.

However, it now seems `https://www.boost.io/releases/` has a `csrftoken` cookie set.  See the file `templates/libraries/detail.html` `{% csrf_token %}` .   After visiting that page and receiving a `csrftoken`, the token is used on all subsequent page views, even /community/ and /news/.   
Could `{% csrf_token %}` be removed from /releases/.

**Comment by vinniefalco** [comment]
This is nice but we need the site to preserve session settings even for non-anonymous users. For example, if someone chooses "version 1.64.0" on the Libraries page, and then they navigate to the Releases page, the dropdown should stay on "version 1.64.0." Perhaps we can do this with a query parameter instead of a cookie. But it needs to be done.

**Comment by sdarwin** [comment]
> Perhaps we can do this with a query parameter instead of a cookie.

Yes, let's try with a query parameter first.

It might be possible with a low-granularity cookie. But there is some risk if the number of boost versions is large enough it won't be cached anymore.

**Comment by sdarwin** [comment]
When someone logs in, please add a cookie `logged-in=1`.     When they log out, clear that cookie.  
The reason: before today, a logged-in user could be detected by the presence of a cookie `config-sessionid.`  After today, at least on staging, any/all users might have a cookie `config-sessionid`.   By adding the new `logged-in` value, caching decisions can still be made.   Otherwise, logged-in status is not known.

**Comment by kennethreitz** [comment]
Sounds like a plan!

**Comment by sdarwin** [comment]
> simply use a cookie for the version preference

It's possible. Only setting the cookie if/when they select a version. Otherwise the preferable and common case without a cookie.

**Comment by GregKaleka** [comment]
> Could {% csrf_token %} be removed from /releases/.

Yes. The version dropdown triggers a POST request for some reason. Changing that to a GET request would let us remove the csrf_token.

**Comment by sdarwin** [comment]
@GregKaleka   This issue was from months ago.   We have now managed to avoid the config-sessionid cookie for anonymous users, switching to specific cookies that remember the boost version (for example 1.86.0).  boost_version=boost-1-86-0.

Testing https://www.boost.io/releases/ as an anonymous user I don't observe a csrftoken being sent.   Great.   In the original issue I wrote "However, it now seems https://www.boost.io/releases/ has a csrftoken cookie set."   That isn't happening now.  

> POST request / GET request

if the user's browser has a cookie stored, it will send that every time, regardless of POST or GET.  For both of those the cookie will be included in the request headers.

A remaining problem might be, that after someone logs out, the browser keeps a csrftoken.   If they continue to send that along with every web request, it may prevent caching.   

closing 'Anonymous users should not set Cookies'

**Comment by GregKaleka** [comment]
> if the user's browser has a cookie stored, it will send that every time, regardless of POST or GET. For both of those the cookie will be included in the request headers.

On this point, just to clarify, Django automatically adds a csrf_token to forms with method="POST". If we change it to GET, then _new_ users will not see the csrf token in the first place. That obviously won't remove cookies for users who visited the site before such a change.
