### ISSUE TITLE
Keep Version between Libraries and Releases pages

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#1040]
When navigating between Libraries and Releases pages, stay on the same Boost version.

These pages already use either query parameters or URL path segments to keep track of version, and are self-consistent on each page.    Notice the URLs:

Libraries: https://www.boost.io/libraries/?category=data&version=boost-1-78-0   

Releases: https://www.boost.io/releases/boost-1-78-0/

All links on the Libraries page: https://www.boost.io/libraries/fusion/boost-1-78-0/

Therefore what is missing?  At least, to adjust the hyperlinks in the header bar at the top of each page where it says "Libraries" and "Releases".  Point to the Boost version the user is visiting instead of 'latest'.

**Comment by sdarwin** [comment]
There may be more than one way to implement this but an idea is to use javascript on the browser side. The header bar examines it's own URL, and notices "version=boost-1-78-0" or "/boost-1-78-0/" in the current URL.  It dynamically update the links in the header bar, adding a query parameter "?version=boost-1-78-0".

**Comment by sdarwin** [comment]
A high granularity cookie, by all users, would disrupt cdn caching.  
On the /docs/ pages, we have take extra steps to avoid that, by loading the profile information out-of-band.  The /docs/ pages have all cookies removed, and yet it still shows the profile image, which is specific to each user.    
In terms of the library pages, they already use the version in the url, in the query parameter:  https://www.boost.io/libraries/?category=data&version=boost-1-78-0  .  All the individual library links as well.   So it's not adding extra data, to use a query parameter. 
Having a URL that points to a version such as boost-1-78-0 is useful, it can be linked to, externally.

**Comment by kennethreitz** [comment]
This has been implemented in #1041, which is usable at: https://www.stage.boost.cppalliance.org/

**Comment by joaquintides** [comment]
Note that this version breakage also happens in scenarios like the following:

* Go to libraries: dropdown at 1.84.0
* Go to a particular library, say Accumulators: dropdown at 1.84.0
* Select dropdown at say 1.81.0, yellow warning appears (correct)
* Go to libraries: **dropdown at 1.84.0**

**Comment by kennethreitz** [comment]
My implementation seems to have some quirks on staging that I couldn't produce locally. Looking into it.

**Comment by kennethreitz** [comment]
okay, it's working now :)

**Comment by kennethreitz** [comment]
updated to use temporary instead of permanent redirects
