### ISSUE TITLE
libs/{libname}/{path} and doc/html/{libname}/{path} redirects are broken

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1042]
This is an extension of #1007. In the old website, the following URLs (for instance)

* https://www.boost.org/libs/multi_index/doc/tutorial/basics.html
* https://www.boost.org/libs/json/doc/html/json/quick_look.html
* https://www.boost.org/doc/html/poly_collection/tutorial.html

get redirected to

* https://www.boost.org/doc/libs/1_84_0/libs/multi_index/doc/tutorial/basics.html
* https://www.boost.org/doc/libs/1_84_0/libs/json/doc/html/json/quick_look.html
* https://www.boost.org/doc/libs/1_84_0/doc/html/poly_collection/tutorial.html

Note that we have two types of libraries according to where their docs are located:

* Normal libraries at libs/{libname}
* So-called "integrated libraries" at doc/html/{libname}. These follow an old initative to construct an integrated BoostBook with all the libraries featuring as individual chapters. The list of integrated libraries can be obtained from https://www.boost.org/doc/libs/1_84_0/doc/html/libraries.html. It's been discussed that integrated libraries should eventually revert to nomal doc location, but this move has not been initiated yet.

My proposal is that we support both redirect schemas in the new website:

1.  libs/{libname}/{path} --> doc/libs/{latest_version}/libs/{libname}/{path}
2.  doc/html/{libname}/{path} --> doc/libs/{latest_version}/doc/html/{libname}/{path}

A smarter approach, which I don't think necessary at this moment, is that the schema 2 reverts to

3.  doc/html/{libname}/{path} --> doc/libs/{latest_version}/libs/{libname}/{path}

when the "backend" detects that the affected library has migrated from integrated to normal (and only in that case).

**Comment by kennethreitz** [comment]
These redirects have been installed. Deploying to staging now.
