### ISSUE TITLE
Profile photo displays not adjusted to the same aspect ratio

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1044]
This can be shown in the library pagelet, I don't know if it happens elsewhere:

![imagen](https://github.com/boostorg/website-v2/assets/3283164/95d49bdf-6bee-4ad9-bc1c-a5ec5c00784a)

**Comment by julioest** [comment]
I'm available to look into this issue—feel free to assign it to me

**Comment by julioest** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/3283164/320221780-95d49bdf-6bee-4ad9-bc1c-a5ec5c00784a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc1NTksIm5iZiI6MTcxMjgyNzI1OSwicGF0aCI6Ii8zMjgzMTY0LzMyMDIyMTc4MC05NWQ0OWJkZi02YmVlLTRhZDktYmMxYy1hNWVjNWMwMDc4NGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDkyMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQ1M2YxN2JmOWY2ZTA3OTJhYTk5N2ZkY2VlZjU4Y2MyNjRjOWZmY2JlM2M5MDc1OGJjNmY2Y2NmMmRhM2RjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V6ipOrKS5uvez6VvaEzyLLYgvSSlFlL4r3WWKjYPcfo)

@joaquintides Quick question, which specific library page url is this screenshot from?

**Comment by joaquintides** [comment]
https://www.stage.boost.cppalliance.org/libraries/unordered/boost-1-84-0/

**Comment by kennethreitz** [comment]
Thanks for the fix @julioest!
