### ISSUE TITLE
tools/{libname}/{path} redirect rules

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1055]
This is an extension of #1042. The old website has the redirects of the following form:

* https://www.boost.org/tools/build --> https://www.boost.org/doc/libs/1_84_0/tools/build/doc/html/index.html

In the new website the link https://www.stage.boost.cppalliance.org/doc/libs/1_84_0/tools/build/doc/html/index.html works OK, but we don't have the redirect from the version-less URL. So, we need these redirect rules:

* tools/{libname} --> doc/libs/{latest_version}/tools/{libname}
* tools/{libname}/{path} --> doc/libs/{latest_version}/tools/{libname}/{path}

**Comment by kennethreitz** [comment]
Working on this now, locally. 


As described, I have `http://localhost:8000/tools/build` redirect to `http://localhost:8000/doc/libs/1_84_0/tools/build`, which 404s. Should it include the `doc/html/index.html` component too?

**Comment by kennethreitz** [comment]
I see, missing the trailing slash. disregard

**Comment by kennethreitz** [comment]
Thanks for catching that! 

https://github.com/boostorg/website-v2/commit/b97e83cbd1e1bda7064b65f3e39baf11f8077b59

Should be fixed now.

**Comment by joaquintides** [comment]
Sorry to be reopening again:

* https://www.stage.boost.cppalliance.org/tools/inspect correctly redirects to https://www.stage.boost.cppalliance.org/doc/libs/1_84_0/tools/inspect/
* But https://www.stage.boost.cppalliance.org/tools/inspect/index.html does not redirect to https://www.stage.boost.cppalliance.org/doc/libs/1_84_0/tools/inspect/index.html

**Comment by kennethreitz** [comment]
taking a look, many thanks

**Comment by kennethreitz** [comment]
Sorry about that. Should be better now, tested with the links above!
