### ISSUE TITLE
Download feed has wrong internal link

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1057]
The Download RSS feed:

https://www.stage.boost.cppalliance.org/feed/downloads.rss

has an incorrect `<link>` parameter:

```
<link>http://www.stage.boost.cppalliance.org/downloads/</link>
```

Should be:

```
<link>http://www.stage.boost.cppalliance.org/releases/</link>
```

**Comment by kennethreitz** [comment]
Nice catch!

**Comment by kennethreitz** [comment]
Fixed here: https://github.com/boostorg/website-v2/commit/b2fd3cbb634ef8a895535cefa1cdbe89dffe9d83
