### ISSUE TITLE
Misalignment in Community/Across the Web

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1058]
The header "On X (aka Twitter)" is split in two lines, which looks bad:

![imagen](https://github.com/boostorg/website-v2/assets/3283164/f5150e1d-9b46-4b46-8cae-0efb1d1ce06d)

It'd be better this way:

![imagen](https://github.com/boostorg/website-v2/assets/3283164/9014730e-14ac-4a17-b4a3-8e08851e2972)

**Comment by kennethreitz** [comment]
The line needs to be shortened to fit on one line. 

https://github.com/boostorg/website-v2/commit/c8827699c6392a140dbd145844554781e61bfcf0
