### ISSUE TITLE
Access to master/develop versions of the library docs

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1061]
**WARNING: NOT TO SOLVE NOW.**

Previously, https://boost.io allowed for access to the develop/master of library documentation through the version drop-down:

![imagen](https://github.com/boostorg/website-v2/assets/3283164/917347e8-1786-43fc-85ae-34007d1b13e7)

In [stage ](https://www.stage.boost.cppalliance.org) these options are gone (as of this writing):

![imagen](https://github.com/boostorg/website-v2/assets/3283164/6cad23cb-3d34-4e0d-ad8d-8f93dc3ab138)

This has been probably done so as to keep the version drop-down lists of Libraries and Releases compatible --if the user selects "develop" in Libraries and then goes to Releases, it's not clear which version should be selected (no master/develop in Releases), plus the behavior may be confusing to users switching between both sections no matter the solution.

Filing this issue so that we don't forget about potential UX solutions that would allows us to reinstate master/develop in the Libraries version drop-down lists

**Comment by kennethreitz** [comment]
`develop` is available on staging now.

**Comment by sdarwin** [comment]
At https://www.boost.io/libraries/, 'develop' and 'master' appear back in drop-down list. This could be OK. However there are unexpected results.
1. if you don't have a cookie "session" with a boost version number, the 'develop' drop-down takes you to an empty page.
2. if you do have a cookie "session" with a boost version number, the 'develop' drop-down displays the list of libraries from the version of boost in your session, which means if the last version you were viewing was 1.35.0, and then choose 'develop', it shows the libraries that were in boost 1.35.0, so boostorg/json, boostorg/beast are missing.

In both cases 1 and 2, it should show the list of libraries from the lastest possible version of boost (such as 1.85.0) or even more up-to-date, an actual newer list from 'master' or 'develop'. If 'develop' and 'master' lists aren't available right now, that's alright, don't add it, show the most recent list of boost libraries (eg. 1.85.0).  Another option is to fall back again to not showing 'develop' 'master'.

**Comment by joaquintides** [comment]
IMHO, we should now remove develop and master from the dropdown lists everywhere (Libraries/Releases, stage/prod) and wait till launch to address this issue.

**Comment by kennethreitz** [comment]
This should be solved in staging, shortly.
