### ISSUE TITLE
Go back to default sans-serif, no Cairo

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1065]
We need to be honest with ourselves. Cairo is worse than the original website font, which is some flavor of Arial, Helvetica used by the default browser / OS sans-serif.

**Comment by kennethreitz** [comment]
@vinniefalco what do you think of the preview images on https://github.com/boostorg/website-v2/pull/1064 ?

**Comment by vinniefalco** [comment]
In case it wasn't clear I think we should ditch Cairo and go with the Arial + Helvetica + default sans-serif.

**Comment by joaquintides** [comment]
@vinniefalco is it ok to close this issue now?
