### ISSUE TITLE
Different version drop-downs in Libraries and Releases

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1080]
As of 2024/05/03, this is the version drop-down in Libraries (stage):
![imagen](https://github.com/boostorg/website-v2/assets/3283164/7dc53ec8-66ee-4f05-90e6-e26a3ebf8ebc)
and this in Releases:
![imagen](https://github.com/boostorg/website-v2/assets/3283164/5c612929-94b7-4f1c-a740-c20820bda22a)
Please remove "develop" so that only numbered versions appear in both sections.

FWIW, boost.io has "develop" **and** "master" in Libraries. Does anyone know where this is controlled? I have the impression (I may be wrong) that this changes from time to time somewhat haphazardly. Thank you!

**Comment by kennethreitz** [comment]
See also: #1096

**Comment by kennethreitz** [comment]
Waiting on staging to reticulate splines for CDN cache to confirm fix. Having trouble with my credentials into Fastly, currently.
