### ISSUE TITLE
Missing indentation in lists

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#1083]
https://www.boost.io/releases/

![Screenshot_20240602_204806](https://github.com/boostorg/website-v2/assets/1589747/6a3d1b6e-772e-4f31-bf2f-1a9e6848eaa5)
![Screenshot_20240602_205325](https://github.com/boostorg/website-v2/assets/1589747/17eb82e5-62c9-454c-b6d3-66e66acfcb31)

The lists of new libraries and updated libraries, as well as the nested lists of updates for each library, are not indented, as they should. Notice that Beast release notes are displayed flat instead of multiple sublists. Here's the release notes from the old website, for comparison.

![Screenshot_20240602_205102](https://github.com/boostorg/website-v2/assets/1589747/c1c6e55b-7a16-4a6e-a4f5-14e8f75c8ecd)

**Comment by joaquintides** [comment]
This is covered by #932

**Comment by julioest** [comment]
@joaquintides Could this be closed? Or waiting to be in production?

**Comment by joaquintides** [comment]
Yes, I'm closing this now Thanks for the heads up!
