### ISSUE TITLE
Poor wrapping of "Join" in the page header on Contributor Guide

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#1086]
https://www.boost.io/doc/contributor-guide/index.html

At the top header, "Join" is poorly wrapped.

![Screenshot_20240603_003440](https://github.com/boostorg/website-v2-docs/assets/1589747/44e84e5e-2bc9-4dd3-8ac7-10989c712fce)

Firefox 126.0.1, Kubuntu 22.04.

**Comment by joaquintides** [comment]
@julioest can you take a look at that? It doesn't show in my local environment (Firefox 126, Windows).

**Comment by julioest** [comment]
@joaquintides Sure thing, I see it on my end (Mac, Chrome). So far from my investigation, it's a weird CSS bug that happens when on these docs/guides
