### ISSUE TITLE
Add a link to Discussion Policy on the Community tab

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#1087]
https://www.boost.io/community/

It would be helpful if the Mailing Lists tile on this page contained a link to the Discussion Policy page (https://www.boost.io/doc/user-guide/discussion-policy.html). In general, the Discussion Policy should be exposed better so that new users and contributors are less likely to miss it.

**Comment by julioest** [comment]
@Lastique Is this the expectation?
![Add a link to Discussion Policy on the Community tab #1087  ](https://github.com/boostorg/website-v2/assets/3632378/5b18b647-218b-41b7-acd9-f6c81a8a47c9)

**Comment by Lastique** [comment]
This may make people confuse the Discussion Policy for yet another ML. I would add a sentence like "Please, read our [Discussion Policy](https://www.boost.io/doc/user-guide/discussion-policy.html) before posting." to the tile description. Or maybe add a [Discussion Policy](https://www.boost.io/doc/user-guide/discussion-policy.html) link (as text) right below the ML icons, in the center. But I'm open to other suggestions.

**Comment by julioest** [comment]
Here are the two options

![Image](https://github.com/boostorg/website-v2/assets/3632378/fd56213e-0881-47d5-a439-427cd3cf0311)
![Image](https://github.com/boostorg/website-v2/assets/3632378/2f6d7782-55f8-4b4f-895a-46a33cae1f22)

**Comment by Lastique** [comment]
Thanks. Both look fine to me. The first one maybe a bit better as it makes the Discussion Policy link more prominent.

**Comment by joaquintides** [comment]
Shouldn't this link be a relative URL so that it'll continue work when we migrate the website to boost.org?

https://github.com/boostorg/website-v2/blob/663d78133ff4486c7b7bc52d9dea953d51bbc363/templates/community_temp.html#L36

**Comment by julioest** [comment]
> Shouldn't this link be a relative URL so that it'll continue to work when we migrate the website to boost.org?
> 
> https://github.com/boostorg/website-v2/blob/663d78133ff4486c7b7bc52d9dea953d51bbc363/templates/community_temp.html#L36

You're right, I've created a new PR!
