### ISSUE TITLE
In-doc tabs in the Learn section don't work

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1101]
Clicking on any of the Windows/Linux/macOS tabs in https://www.stage.boost.cppalliance.org/doc/user-guide/getting-started.html don't work

![imagen](https://github.com/boostorg/website-v2/assets/3283164/baed63d7-6bca-4b9c-a9b5-294be6859e92)

As far as I can tell all such tabs throughout the Learn docs are affected. This used to work sometime in the past.

**Comment by vinniefalco** [comment]
This goes in website-v2-docs
