### ISSUE TITLE
Expandable items in Learn docs TOC don't work

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1104]
If I go to https://www.stage.boost.cppalliance.org/doc/user-guide/intro.html and click on "Common Scenarios":

![imagen](https://github.com/boostorg/website-v2/assets/3283164/c0e7f678-fe93-4132-87bc-7a745d67abe2)

nothing happens (item is not expanded). This is a regression AFAICS.

**Comment by julioest** [comment]
This has been fixed
