### ISSUE TITLE
Antora navbar does't stick to top in Learn docs in mobile

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1109]
As shown here:

![imagen](https://github.com/boostorg/website-v2/assets/3283164/054e051c-37b0-4dc1-b9fb-2fdb8c3de241)

The navbar should stick to the top without any intervening space.

**Comment by julioest** [comment]
@joaquintides Can this be closed?

**Comment by joaquintides** [comment]
Yes, thank you!
