### ISSUE TITLE
Replace "03", "11", etc. icons with "C++03", "C++11", etc.

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1111]
We received feedback on Reddit that these green icons are not self explanatory

![imagen](https://github.com/boostorg/website-v2/assets/3283164/ad814d94-9f37-4725-ac90-3771bf1bd970)

Replace them throughout the site with "C++03", "C++11", etc.

**Comment by vinniefalco** [comment]
That's gonna repeat the text "C++" quite a lot. Well, lets see how it looks.

**Comment by rbbeeston** [comment]
How about something like this?

![Image](https://github.com/boostorg/website-v2/assets/121198190/6553cfb5-440f-49ac-af70-b1e20e594578)

**Comment by vinniefalco** [comment]
Oh my god... that is offensive, lol.

First of all, let's consider the source of the feedback. Reddit. I rather like how it looks now with just the number in the lozenge. It is tasteful and doesn't draw too much attention, yet still gets the job done. If it were up to me I would leave it as-is.

However there is an argument to be made that it should say "C++03", "C++11", "C++14" and so forth. We can try this, but following these guidelines:

1. Elongate the current lozenge to accommodate the additional text
2. Use a lower contrast color for the characters "C++". For example we use the dark color for the "11" text and white for the "C++" text. This helps de-emphasize the new problem of repetition of "C++".
3. We need to consider how dark mode will look with this change. Perhaps different colors for dark mode are needed.

**Comment by rbbeeston** [comment]
I like the idea of extending the chip, perhaps the C++ could be de-emphasized with a similar shade so it's visible but not striking. Where did that green come from? I haven't seen it used anywhere else.

Something like this could work with dark mode as well by swapping the colors to whatever the primary color we are using for dark mode

![Image](https://github.com/boostorg/website-v2/assets/121198190/8abcc66c-497a-4150-b137-c6951a91ed72)

**Comment by joaquintides** [comment]
I like this because "C++" is there to help users understand what the thing's about, while on the other had is light colored enough that it doesn't clutter the page when duplicated many times over.

**Comment by vinniefalco** [comment]
Yes these samples are a great start! The number font and style needs to exactly match what we already have though. And can we condense and thin out the "C++" part so the lozenge is as narrow as possible? Also please use the same colors as on the site now. We reserve the Boost Mustard color for Very Important and Rare Things (like library names).

**Comment by rbbeeston** [comment]
Will do, I was just throwing together something quick as an example. I agree that the "C++" is a bit long. I checked Font Awesome to see if they had an Icon that would work better, but they don't have one, but they do for a lot of other modern languages..... I may just reduce the font size of the "++" so it's not as long. 

I did manage to find where the green came from, it's in the boost assets on the twitter banner. #00de97
The website is a bit different, using #5ad599
Should that be considered and 'official' secondary color?

**Comment by rbbeeston** [comment]
may as well assign this to myself, I've gotten this far with it...

**Comment by vinniefalco** [comment]
Try an image, rendering with ultra narrow sans-serif font. Alternatively if there is a way to apply a matrix transform to text via CSS try scaling it 0.5 horizontally?

**Comment by rbbeeston** [comment]
I may build an svg. It would scale better, and we could color it however we want.

**Comment by vinniefalco** [comment]
SVG is a good idea yes, but any preview (such as the one above) needs to show it as a rendered image at the equivalent size, in the lozenge, because once you shrink it then it will not bear much resemblance to the larger preview. For example, I personally like the first one above, but those plus signs are going to get lost in the sauce.

Note that users expect version labels like "C++17" to be similar to a particular styling. Check out cppreference.com :

https://en.cppreference.com/w/cpp/container/span
![image](https://github.com/boostorg/website-v2/assets/1503976/f13100aa-cbc7-4dc6-b817-06313062a268)

Close up:

![image](https://github.com/boostorg/website-v2/assets/1503976/0445d38a-4eca-4840-a904-41a4da89a8b6)

Small, unobtrusive sans-serif text. In this case the plus signs are kind of obnoxiously large, we can probably do something about that.

**Comment by rbbeeston** [comment]
What about a hover effect? So the"C++" slides out when you mouse over it? The space already resembles a button so it may be intuitive to check

here's a scaled down version of the first one. The plusses are ok at this size.

![Image](https://github.com/boostorg/website-v2/assets/121198190/de682e4d-0a9c-4767-806b-13bdcc5c7f0c)

**Comment by vinniefalco** [comment]
The hover is an interesting idea but we should probably not get too fancy. I was thinking along these lines:

![image](https://github.com/boostorg/website-v2/assets/1503976/3abddca7-e100-4f09-8ba6-489efb75610c)

**Comment by rbbeeston** [comment]
lol, I just noticed there is a tooltip on it as well. so I guess people don't actually think to hover over it.

![Image](https://github.com/boostorg/website-v2/assets/121198190/3e733e1f-52da-47c1-a72e-3f2eb11e65c0)

**Comment by joaquintides** [comment]
One question: are these icons generated sort of on the fly based on the source text ("03", "11", etc.) or do we have a preset image stock set from which we select? If the latter, we need to have C++03, C++14, C++17, C++20, C++23 (and it won't hurt to already have C++26 and C++29 for the future).

**Comment by vinniefalco** [comment]
They should be implemented using CSS and HTML, not images. It is just text on top of a rounded rect. You can see that it is selectable: 
![image](https://github.com/boostorg/website-v2/assets/1503976/8e7ebb64-d1ee-4a0d-9dd2-9cff51953a7e)

**Comment by rbbeeston** [comment]
@vinniefalco are you good with this?


![Image](https://github.com/boostorg/website-v2/assets/121198190/92852656-d241-4f0d-91ee-40263f1f7da0)

**Comment by vinniefalco** [comment]
no way to know until we see it

**Comment by vinniefalco** [comment]
ON yes that loos good. Can we use tabular figures?

**Comment by rbbeeston** [comment]
I'm using the same font and squishing it with CSS, which is why the tabular spacing is off.  I'll see if I can adjust the kerning a bit to make it more consistent.

**Comment by rbbeeston** [comment]
@vinniefalco any preference? I'm leaning toward the middle option.

![Image](https://github.com/boostorg/website-v2/assets/121198190/af23ac72-3e1a-4e85-8751-8d917578cb44)

**Comment by vinniefalco** [comment]
They all look the same to me. Add "11" so we can see it side by side, because without tabular figures the number "1" is very thin.

Also, can we tighten up the horizontal spacing? The lozenge is too long

**Comment by rbbeeston** [comment]
here is the spacing with all 11's, I'll adjust the lozenge spacing separately once we decide on this. I'm liking the second and third options.

![Image](https://github.com/boostorg/website-v2/assets/121198190/9cccfe79-e71f-4819-a7c4-e50f7d8aac0d)

**Comment by vinniefalco** [comment]
What I am looking to see is "C++03" and "C++11" next to each other vertically.

**Comment by vinniefalco** [comment]
Notice how "11" is more narrow than "03." This is because the digits are proportional not tabular. 

![image](https://github.com/boostorg/website-v2/assets/1503976/3901a62e-03fc-4ebe-93d2-b9a23610b566)

**Comment by rbbeeston** [comment]
ok, so you are wanting to change to a monospaced font for the lozenges?

**Comment by vinniefalco** [comment]
LOL... NO!!! I want to use the tabular figures in the default sans-serif font, not change to a new font!
https://stackoverflow.com/questions/17626159/can-you-specify-tabular-lining-figures-for-webfonts

**Comment by rbbeeston** [comment]
OH! ok, TIL, haven't seen that one before, I'll put something together with that.

**Comment by vinniefalco** [comment]
Ah... well, this might help explain it:
https://www.monotype.com/resources/expertise/how-use-figure-styles-illustrator
https://www.reddit.com/r/typography/comments/zhu7ck/today_i_learned_about_tabular_figures/

**Comment by rbbeeston** [comment]
here you go. I'll see about getting the lozenges narrower

![Image](https://github.com/boostorg/website-v2/assets/121198190/e41825f0-e0ae-4f80-a57a-0e61b2a800c7)

**Comment by rbbeeston** [comment]
is this narrow enough?

![Image](https://github.com/boostorg/website-v2/assets/121198190/864b6503-696e-4001-a759-a7e00433d280)

**Comment by vinniefalco** [comment]
The last one is looking better, can we kill some of that space between the "++" and the "03"?

**Comment by rbbeeston** [comment]
All good?

![Image](https://github.com/boostorg/website-v2/assets/121198190/16f5c637-5318-4937-94f0-95f4a92d7523)

![Image](https://github.com/boostorg/website-v2/assets/121198190/9a44bd0a-0587-44c9-a15a-514527bf76a3)

**Comment by vinniefalco** [comment]
Yes! How does this look at 100%?

**Comment by rbbeeston** [comment]
![Image](https://github.com/boostorg/website-v2/assets/121198190/e18c8f10-1b04-4b6c-9714-0a0352f56f1a)



![Image](https://github.com/boostorg/website-v2/assets/121198190/e3944575-e4a5-49b8-bd56-89d1b13880cb)

**Comment by rbbeeston** [comment]
![Image](https://github.com/boostorg/website-v2/assets/121198190/da5b97b1-4493-408d-bada-cbd0db9760ed)

**Comment by rbbeeston** [comment]
Minor UX thing, but in the libraries, in the card view, perhaps make the whole card clickable, and in the list view make the row clickable. As well as having some type of card or row level hover effect on each.

**Comment by vinniefalco** [comment]
> make the whole card clickable

Please open an issue

Yes those lozenges look great now!

**Comment by joaquintides** [comment]
Reopening as there's one page where the lozenges still look bad on Firefox

![imagen](https://github.com/user-attachments/assets/e2eb2ed7-6d38-4d8c-8a21-346ea46a568a)

**Comment by vinniefalco** [comment]
I don't understand why this happens. Can I please see the HTML?

**Comment by rbbeeston** [comment]
completed Jul 23rd
