### ISSUE TITLE
Remove "* The download links are supported by grants from The C++ Alliance." from release notes

### ISSUE THREAD

**Issue by julioest** [boostorg/website-v2#1116]
Remove the following text (without quotes) from release notes:

"* The download links are supported by grants from [The C++ Alliance](https://cppalliance.org/)"

Reference: per @sdarwin https://github.com/boostorg/website-v2/pull/1113#issuecomment-2192454665
> If the following new text is found in the release notes "* The download links are supported by grants from [The C++ Alliance](https://cppalliance.org/). " it should be removed, in the same way the actual download links were, since the message goes with the actual downloads.
https://github.com/boostorg/website-v2/pull/1113#issuecomment-2192454665

**Comment by kennethreitz** [comment]
@sdarwin can you run manage.py import_release_notes against staging shortly? we should be able to close this once that's done

**Comment by sdarwin** [comment]
> import_release_notes 

done
