### ISSUE TITLE
10-day grace period for user deletion

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1121]
After #965 is implemented, extend it so that instead of immediate deletion a 10-day grace period is provided:

* The data will become invisible to other users (except for public comments) for 10 days.
  * Comment from Joaquín: there's no data to hide from other users --contributions will remain anyway and there are no other signs of presence of a particular user (like consulting their profile etc.)
* During this 10-day grace period the user can cancel the deletion request.
* After 10 days the data is actually deleted, and perhaps a follow-up email is sent.
* Optionally we can also have a "Delete Now" button

**Comment by rbbeeston** [comment]
Assigning to @gavinwahl, as he completed #965
