### ISSUE TITLE
Explicit acceptance of Terms of Use for registered users

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1127]
Currently, users can go about the website wthout even noticing there are some (reasonable) terms of use associated to it. This is not a major problem for unregistered users, who can do little else than reading info anyway, but we want registered users to notice and abide by these terms.

My suggestion would be to add it like this (subject to UI discussions on best placement etc.)

![imagen](https://github.com/boostorg/website-v2/assets/3283164/b2f38699-312e-4d68-aef1-39c8fe6a7a85)

Where "Terms of Use" opens up the Terms of Use in a different window, and the buttons "Use GitHub", "Use Google" and "Sign up" are not enabled until the user clicks the check.

**Comment by rbbeeston** [comment]
That's a good start, probably want to center the terms of service, and disable the the buttons until the terms are clicked (do we want to require clicking on the terms first?)

**Comment by joaquintides** [comment]
> Do we want to require clicking on the terms first?

I don't think that's necessary, as the Terms of Use are readily available and easy to locate before and after the registration process.

**Comment by rbbeeston** [comment]
ok, so This is simple enough, design-wise, it can be built from scratch just by coding it. while I can mock something up with it, another thing we should consider is putting together a style guide first. It's a matter of what the priorities are. 

I know there is a push to get this out soon, so I or Julio can build something that looks and works fine for the time being, and then consider changes once the style guide is put together, or focus on the style guide first.

**Comment by kennethreitz** [comment]
Awaiting further review of #1143

**Comment by rbbeeston** [comment]
this has already been completed
