### ISSUE TITLE
Hardening of registering process

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1128]
There are two problems with the current registration problem:

1. (Major) The process does not go through to an email validation phase (typically implemented via some callback sent to the provided address that the user needs to go through in order to enable the account).
2. (Minor) The email textbox has both client-side and server-side validation with unclear (to me) rules:
   * Typing "john" or "john@" triggers the client side validation ("Enter an email address" right at the bottom of the editbox).
   * Typing "john@x" triggers the server-side validation (A message in read appears with "Enter a valid email address" above the editbox).

To write: a more precise spec of how we want to implement this hardening.

**Comment by joaquintides** [comment]
Yes, this only applies to the email-based registration process.

**Comment by kennethreitz** [comment]
I'm currently looking into the functionality available in this Django package: https://github.com/LeoneBacciu/django-email-verification

It looks like a solid choice for what we're trying to accomplish here.

**Comment by kennethreitz** [comment]
Actually, Django-Allauth (the authentication library we use) has functionality that does this already, it's just disabled: https://docs.allauth.org/en/latest/account/configuration.html

**Comment by rbbeeston** [comment]
This is already in progress by @daveoconnor. Dave can you also close this when once these features are merged?
