### ISSUE TITLE
Revisit cookie usage for CDN

### ISSUE THREAD

**Issue by kennethreitz** [boostorg/website-v2#1146]
We want to revisit our usage of `config-sessionid` on the website, so the CDN can be used for more users.

**Comment by joaquintides** [comment]
Hi @kennethreitz I observed this new faulty behavior, which I think may be connected to  #1169. Using Firefox, in case it matters:

* https://www.stage.boost.cppalliance.org/libraries/mini/?version=boost-1-85-0
![imagen](https://github.com/user-attachments/assets/92a67e94-77ba-431b-920d-61f05974c66d)

* I click in "Grid view" and the URL changes to https://www.stage.boost.cppalliance.org/libraries/mini/?version=boost-1-85-0&reset_view=1 but the display does not:
![imagen](https://github.com/user-attachments/assets/d1d4108c-7591-46bb-9d80-9a64273f72fc)

* If I click again on "Grid view", the URL changes again and the display is now correct:
![imagen](https://github.com/user-attachments/assets/8d3464a9-3ddd-43dd-9024-48c461a353ca)

**Comment by kennethreitz** [comment]
@joaquintides having trouble reproducing this locally, but yes it's happening for me on staging too. @sdarwin do you think this could be related to CDN caching?

**Comment by sdarwin** [comment]
In your local /etc/hosts file set this entry:  

`34.120.246.69 www.stage.boost.cppalliance.org`

The browser will go directly to Google, bypassing Fastly.    It seems the issue still exists.  

Another problem, on production, if I go to https://www.boost.io/libraries/mini/?version=boost-1-85-0 as the first visited page (not clicking grid view, list view, )   it shows:  

![Screenshot from 2024-07-31 06-58-13](https://github.com/user-attachments/assets/b50d3f14-e73a-4023-a6cb-c840ea503112)

That means there could be a pre-existing issue about going to the /mini/ view,  right after opening the browser, as the first page.    It might be connected to this issue.

**Comment by sdarwin** [comment]
1. When switching from category view to list view, I click the list view button and it supposedly goes to the list view, briefly.   Yet, returns a 302 redirect, instantly returning to category view.

```
 - - [08/Aug/2024:21:59:30 +0000] "GET /libraries/mini/ HTTP/1.0" 302 0 "https://www.cppal-dev.boost.cppalliance.org/libraries/by-category/?version=boost-1-84-0" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
 - - [08/Aug/2024:21:59:30 +0000] "GET /libraries/mini/ HTTP/1.0" 302 0 "https://www.cppal-dev.boost.cppalliance.org/libraries/by-category/?version=boost-1-84-0" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
 - - [08/Aug/2024:21:59:31 +0000] "GET /libraries/by-category/?version=boost-1-84-0 HTTP/1.0" 200 350253 "https://www.cppal-dev.boost.cppalliance.org/libraries/by-category/?version=boost-1-84-0" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
```

At this time, I have a cookie `library_view=libraries-by-category`.    It somewhat seems that the "category" cookie overrides the choice of the URL /libraries/mini/ .     

Or vice versa. Sometimes you get stuck in the /mini/ view.    

2. The next result is more unusual.  

After clearing History in Firefox, 
- visited the homepage
- visited the Releases page.  
- Switched to 1.83.0. It added a cookie about the boost version.
- visited the Libraries page.  Now something surprising happened.   It sends a series of redirects, switching to Category view.

See screenshot. Notice on the right side, which cookies are set.  Nothing about Library View or Category View was there initially.   And yet, a few 302 redirects occur.

![Screenshot from 2024-08-08 16-27-33](https://github.com/user-attachments/assets/9657e9b7-d445-4053-b53b-20af26c183d6)

 The final 302 in that picture is sending a "set-cookie | library_view=libraries-by-category; Path=/"

**Comment by daveoconnor** [comment]
Switching between the library views is now working. Was unrelated to the CDN.

**Comment by sdarwin** [comment]
> Switching between the library views is now working. 

From a few tests, this seems to be working correctly.  Awesome!  Closing issue.
