### ISSUE TITLE
Tailwind server issues

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1147]
As a means of addressing tailwind issues we should do the following:

1. Add static/style.css to gitignore
2. Have the build process generate the static/style.css when being moved onto the server (however makes sense) so that it's built fresh based on the current code base.

**Comment by kennethreitz** [comment]
That sounds like a good plan to me. Maybe we can make the `yarn build` part of the docker image build

**Comment by rbbeeston** [comment]
That would be perfect if that will work

**Comment by kennethreitz** [comment]
https://github.com/boostorg/website-v2/pull/1158
