### ISSUE TITLE
Fix Navigation Shift Issue on Index Pages of User Guide and Contributor Guide

### ISSUE THREAD

**Issue by julioest** [boostorg/website-v2#1148]
When navigating to the index pages of the User Guide or Contributor Guide, the left-side documentation navigation shifts up and gets partially hidden beneath the website’s main navbar.

### Steps to Reproduce:
1. Go to the root link of User Guide or Contributor Guide documentation. e.g. https://www.boost.io/doc/user-guide/index.html
2. Observe the navigation bar shifting up and getting obscured by the main website’s navbar.

### Screenshots
![intro html](https://github.com/user-attachments/assets/9223bb4d-c6c7-4a85-93b2-2967745c4954)
![index html](https://github.com/user-attachments/assets/f8016c9f-23e0-451a-aeb4-259f009e8544)

**Comment by julioest** [comment]
No longer needed since side nav was removed from Antora templated

**Comment by joaquintides** [comment]
Hi @julioest we have just decided we'll bring the side nav back (see the Slack group), sorry for the noise!

**Comment by julioest** [comment]
No worries! I'm on it 👍

**Comment by julioest** [comment]
This will be fixed in https://github.com/boostorg/website-v2-docs/issues/266

**Comment by julioest** [comment]
@rbbeeston Can this be closed now with our latest changes? 😄

**Comment by rbbeeston** [comment]
Correct. No longer an issue.

**Comment by julioest** [comment]
@joaquintides This is good to close
