### ISSUE TITLE
bottom spacing of border bottom in community cards

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1151]
currently the library cards look like this:
![Screenshot 2024-07-17 at 1 51 30 PM](https://github.com/user-attachments/assets/932d1f3a-f971-4e89-9c64-77ff2af20440)

but the border bottom is very crowded. it would look better like this:
![Screenshot 2024-07-17 at 1 51 46 PM](https://github.com/user-attachments/assets/72ee8e54-a05d-48dc-9080-8ed98897294c)

**Comment by vinniefalco** [comment]
I agree, although in the long term these cards are sort of ad-hoc and don't adhere to a well-defined visual style.
