### ISSUE TITLE
UI/UX for in-progress release notes

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1155]
This URL in the old website:

https://www.boost.org/users/history/in_progress.html

displays the in-progress release notes for the next Boost version. The current redirection rules for the new website map

https://boost.io/users/history/in_progress.html

to

https://www.boost.io/releases/boost-in-progress/

which is a 404.

This need yet to be specified. Some issues to consider that are potential blockers/difficulties:

* If we add "in_progress" to the Releases drop-down list, we'll get a mismatch when switching to "Libraries".
* I think the in-progress release notes are not being perodiocallly (like, daily) copied to the new website.

**Comment by kennethreitz** [comment]
> If we add "in_progress" to the Releases drop-down list, we'll get a mismatch when switching to "Libraries"

We can add support for this without affecting the drop-downs.

**Comment by joaquintides** [comment]
> We can add support for this without affecting the drop-downs.

Kenneth and I had a conversation on this, this is a more detailed description of how the dropdown-less solution would work:

* Some page, for instance https://www.stage.boost.cppalliance.org/releases/in_progress/, would display the in-progress release notes.
* This page has the same layout as the Releases section, but it doesn't change and is not affected the version cookie. Clcking on "Releases" or "Libraries" from here goes to the normal behavior (displaying information for whatever shipped version the user has their cookie set on).

**Comment by joaquintides** [comment]
> I think the in-progress release notes are not being perodiocallly (like, daily) copied to the new website.

Sam confirms that

https://github.com/boostorg/website/blob/master/users/history/in_progress.html

is available and can be used by the new website just like the rest of release notes pages.
