### ISSUE TITLE
Continuation of "Terms of Use" Updates

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1167]
Additional functionality for the the new boost website Terms of Use acceptance. The following features to be added or verified:

**JS enabled browsers:**  
1. Turn the ToU page into a pop-up modal for viewing.
2. turn the github and goggle log ins into popups, rather than having to navigate to a separate page

**Email Registration Process:**
1. when a person registers via email, they receive a link with a time limitation (TBD) to validate it. 
2. if a person uses an expired link, they go to a page asking them to re-register.
3. if a person attempts to register an email that has already been registered, that email address will receive an email that an attempt was made to re-register that email. Perhaps include instructions to recover the password in case it was forgotten.
4. when a person clicks a valid registration link, they go to a page that validates the registration and notifies the user, and then invite them to login (or automatically log them in)

There may need to be some discussion as what pieces will be front end, and which will be back end, and will overlap with #1127 and #1128

[Figma display of process](https://www.figma.com/design/zXlP2terFel1MGUc5n1SyQ/Terms-of-Use-Workflow?node-id=0-1&t=QghEvKCm8EWiGfZ4-0)

Other considerations:
1.  Should JS users be stored so they can be notified to updated Terms of Use as a site popup, or would all users be notified via email?

**Comment by Lastique** [comment]
> 1. Should JS users be stored so they can be notified to updated Terms of Use as a site popup, or would all users be notified via email?

If an email is registered, notifications about changes in legal documents such as ToU must be sent to that email. That is the common practice. This is regardless of any indication on the website itself.

**Comment by daveoconnor** [comment]
This is now mostly complete, the exception being the email notification which is covered by ticket #986, so I'm closing this.
