### ISSUE TITLE
1.86.0.beta1 release notes not showing

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1171]
![imagen](https://github.com/user-attachments/assets/6f3f6c5b-191d-4b4f-9581-1b2488ff8b2e)

I _guess_ this is because the release notes in boostorg/website are stored in

https://github.com/boostorg/website/blob/master/users/history/version_1_86_0.html

rather than

https://github.com/boostorg/website/blob/master/users/history/version_1_86_0_beta1.html (404)

Maybe we need to trim "_beta*" for purposes of locating the associated release notes.

**Comment by kennethreitz** [comment]
Will confirm on staging shortly

**Comment by kennethreitz** [comment]
This is not yet working. I think there's an extra `.` in there, possibly. Still investigating.

**Comment by kennethreitz** [comment]
The resulting cache key should for `1.86.0.beta1` should be `release_notes_boost-1-86-0` now

**Comment by kennethreitz** [comment]
Reproduced locally

**Comment by joaquintides** [comment]
Hi @kennethreitz any progress on this? Still not working for me on stage

**Comment by rbbeeston** [comment]
@GregKaleka I just want this to be on your radar for the next release. If we get a beta, this will need to be done, or if there is a way to preemptively take care of it, that would be helpful.

**Comment by GregKaleka** [comment]
This should be fixed, but we'll need to verify once we have a beta release in the list again.
