### ISSUE TITLE
Include plausible script in boost.org 

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#1173]
Add analytics javascript snippet in `<head>` section, to https://github.com/boostorg/website

`<script defer data-domain="original.boost.org" src="https://plausible.io/js/script.js"></script>`

The reason for "original.boost.org" is so the snippet will be valid now and also after a migration.  Generally, traffic is not going to that url, but if plausible simply refers to that as an identifier or uuid it should not break data collection.  We will see after deployment if it needs to be adjusted.  

The old website probably has multiple header sections to update.  Such as docs pages. for example:   https://www.boost.org/doc/libs/1_83_0/doc/html/accumulators.html  

cc. @rbbeeston  @julioest

**Comment by joaquintides** [comment]
Implemented in https://github.com/boostorg/website/pull/868

**Comment by joaquintides** [comment]
https://github.com/boostorg/website/commit/3735bdf32ca376db3c5e7acef829630112b8609a
