### ISSUE TITLE
Host static_content locally

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#1175]
In config/settings.py there are a number of "STATIC_CONTENT" settings.  They refer to an S3 buckets.

Add a new config setting such as STATIC_CONTENT_LOCAL=True/False , and similar settings, which allows local development from a local filesystem and do not require an S3 bucket.

Example settings: 

```
STATIC_CONTENT_AWS_ACCESS_KEY_ID = env(
    "STATIC_CONTENT_AWS_ACCESS_KEY_ID", default="changeme"
)
STATIC_CONTENT_AWS_SECRET_ACCESS_KEY = env(
    "STATIC_CONTENT_AWS_SECRET_ACCESS_KEY", default="changeme"
)
STATIC_CONTENT_BUCKET_NAME = env("STATIC_CONTENT_BUCKET_NAME", default="changeme")

STATIC_CONTENT_REGION = env("STATIC_CONTENT_REGION", default="us-east-2")

STATIC_CONTENT_AWS_S3_ENDPOINT_URL = env(
    "STATIC_CONTENT_AWS_S3_ENDPOINT_URL", default="https://s3.us-east-2.amazonaws.com"
)
```

**Comment by gavinwahl** [comment]
@sdarwin do you want to talk through what this entails?

**Comment by sdarwin** [comment]
@gavinwahl , are you on Slack?  We could chat there.  It's late in the week, maybe on Monday.

There are instructions to run website-v2 locally, here: https://github.com/boostorg/website-v2/blob/develop/docs/development_setup_notes.md

This Django website depends on S3, to display boost library documentation.

The website uses S3, to display the user guide and contributor guide.

During testing, how could that be set up locally instead?  In other words, retrieve S3 content from the local filesystem, instead of across the internet to S3?

Option 1:  Install and run a service on your own local machine, that serves files using an S3 api.  Point your docker-compose environment at that API.  Maybe this would be the best choice, if possible.

Option 2:  What was mentioned above.  Add a variable.  Such as STATIC_CONTENT_LOCAL=True

If that variable is TRUE, then have the django code access the S3 content locally somehow, on the same filesystem as the web server.  

In either of those cases, a developer would no longer need access to S3, and that would solve the issue.

**Comment by sdarwin** [comment]
@gavinwahl , thinking about this issue more,  there might be a much easier solution.   If I create yet another set of AWS keys that have read-only access to the staging buckets.  A local developer could point their docker-compose environment at the live S3 buckets.  Dev tests that involve write-access are prevented.  But the files in question are generally being read, not written. They are documentation.  So it should be enough.

**Comment by gavinwahl** [comment]
@sdarwin is there anything left to do on this?

**Comment by sdarwin** [comment]
It should be ok. I have created new aws keys for read-only access to STATIC content. if anyone needs a copy, DM me in Slack.
