### ISSUE TITLE
Alignment problems with HTML-based documentation rendering on mobile

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1187]
As of today (2024/08/14), stage has some alignment problems when rendering HTML-based documentation on mobile devices:

![imagen](https://github.com/user-attachments/assets/2a9f9e71-4168-4153-8412-4a2ec6e847b1)

* The header occludes part of the documentation.
* There are no left or right margins.

**Comment by joaquintides** [comment]
HTML-docs still have zero margin on mobile devices. This is https://www.stage.boost.cppalliance.org/doc/libs/1_86_0/doc/html/accumulators.html in my iPhone (black frame added by me):

![imagen](https://github.com/user-attachments/assets/ff73db86-72ad-4781-b2ce-409b9bfe7d87)

**Comment by rbbeeston** [comment]
@julioest perhaps we need some x-axis padding in the docs at mobile sizes

**Comment by julioest** [comment]
@rbbeeston After reviewing the issue, it’s clear that to fix this properly, we need to target the styling for docs built with boostbook separately. This will be a bit challenging since the navbar is no longer positioned as absolute. Here’s the HTML structure:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/htm14/ loose.dtd">
<html>
<head></head>
<body alink="#0000FF" bgcolor="white" link="#0000FF" text="black" vlink="#840084">
  <!-- BEGIN Manually appending items -->
  <div class="bg-gray-200 dark:bg-black topnavbar"></div>
  <!-- END Manually appending items -->
  <hr>
  <div class="spirit-nav"></div>
  <div class="chapter"></div>
  <div class="copyright-footer"></div>
  <hr>
  <div class="spirit-nav"></div>
  <svg id="SvgjsSvg1001" width="2" height="0" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.dev" style="overflow: hidden; top: -100%; left: -100%; position: absolute; opacity: 0;"></svg>
  <div id="screenity-ui"></div>
</body>
</html>
```

**Comment by rbbeeston** [comment]
@julioest we may be able to use the .topnavbar class as a means of targeting below it, or I could use something like body.article in the header nav to target it from that end.

**Comment by rbbeeston** [comment]
These issues have been managed, I believe it's ok to close. Any additional issues should go in a separate ticket.
