### ISSUE TITLE
clicking on Odeint on the release page for 1.86 leads to a missing page

### ISSUE THREAD

**Issue by Hailios** [boostorg/website-v2#1189]
clicking on Odeint leads to a missing page
https://www.boost.io/releases/boost-1-86-0/
leads to https://www.boost.io/libs/odeint/

**Comment by mborland** [comment]
It should redirect to: https://www.boost.io/libs/numeric/odeint/

**Comment by joaquintides** [comment]
This issue belongs in https://github.com/boostorg/website, keeping it here as the fix is already in wait for merge there.
