### ISSUE TITLE
Nav bar active links not marked properly

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1200]

**Comment by daveoconnor** [comment]
![Image](https://github.com/user-attachments/assets/a25ba5af-f770-4f47-9990-da4db61a84c1)

Looks like it is being styled, it has the `is-current-page is-active` classes applied on the `<li>`, although the visual difference is very small. Do you want me to make it orange to match the active link in the header nav?

**Comment by vinniefalco** [comment]
Are we talking about the table of contents on the left side?

**Comment by julioest** [comment]
> Do you want me to make it orange to match the active link in the header nav?

Hi @daveoconnor! Just a heads up, we decided earlier to manage this behavior through boostlook with a caret

**Comment by vinniefalco** [comment]
What is this?
![image](https://github.com/user-attachments/assets/75cc8f64-a24e-49dd-bfda-b6b3c06c1de0)

**Comment by julioest** [comment]
Hey @vinniefalco. That's the toc for the article itself

**Comment by vinniefalco** [comment]
its ugly.. why is it there? Previously, this was a nifty control to the right. I prefer that, if it is going to be visible. However, one of the options is to disable that control, which I prefer even more over having it at all (for URL). If that option disables the control it should not be visible at the top of the page.

**Comment by julioest** [comment]
✓ Fixed: Nav bar active state indicators working correctly.
TOC improvements moved to: boostorg/website-v2-docs#341

Closing.
