### ISSUE TITLE
more UI fixes

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1205]
**Standardize card views on home page**
Different greens, different alternating styles that don't add anything , different card widths. 
![image](https://github.com/user-attachments/assets/1dd76271-dd00-4161-9f48-e62973ee61cf)

**Make text style match**
highlighted section be bold blue like on the other library page
![image](https://github.com/user-attachments/assets/e4d897d8-e1d7-4e88-8741-412bb7d6727e)

**Comment by vinniefalco** [comment]
The background box looks like ass
![image](https://github.com/user-attachments/assets/3dd5cc29-6d40-44ed-98e7-8c8d4d934a2f)

**Comment by rbbeeston** [comment]
that's not actually there, just highlighting what needs to be done.
Here's how it actually looks:
![image](https://github.com/user-attachments/assets/eee56a8c-6871-44c0-8022-c444d9ffc7c8)

how it should look:
![image](https://github.com/user-attachments/assets/c1eb95c5-7f1f-4e6e-802f-a26667a904a3)

**Comment by vinniefalco** [comment]
oh, phew :) That's quite bold, no?

**Comment by rbbeeston** [comment]
here it is in place
![Screenshot 2024-08-26 at 11 58 25 AM](https://github.com/user-attachments/assets/bdfa5110-cfca-449d-99db-943812bab986)

**Comment by vinniefalco** [comment]
I agree that maybe it should be bold, to distinguish it from a regular inline link. However, I'm going to want to use one of those fancy variable fonts which lets me dial in the precise amount of boldness to balance it with the rest of the page :) Although after I see it in my own browser it might be fine as-is.

**Comment by rbbeeston** [comment]
if you want to go that route, we should also set a single variable font for the site. Currently it's set to a list of fonts, and I doubt any of them are the variable style in the browser:
'-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'Oxygen-Sans', 'Ubuntu', 'Cantarell', '"Helvetica Neue"', 'sans-serif

**Comment by vinniefalco** [comment]
I will revisit the site font after we lock down the antora/asciidoc styling

**Comment by rbbeeston** [comment]
closing this issue, going to create a new issue with more specific font instructions based on discussions
