### ISSUE TITLE
Two contact links

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1221]
We have to "Contact" links at the footer:

![imagen](https://github.com/user-attachments/assets/36fbfb9e-a428-4ec7-9fbc-2830fa21bae6)

The first one goes to this lame page: https://www.stage.boost.cppalliance.org/help/. The second one goes [here](https://www.stage.boost.cppalliance.org/doc/user-guide/reporting-issues.html), and is more about bug reporting with the libs, not the website itself.

My proposal is:

* Keep the first "Contact" but provide a nicer page for this, including en email address, where to file issues with the website itself, link to library-related bug reporting, etc.
* Rename the second "Contact" as "Bug report"

**Comment by rbbeeston** [comment]
It would be helpful to get some guidance on the contact page and where those links should point to.

**Comment by vinniefalco** [comment]
Can we just copy what is on the old site?

**Comment by rbbeeston** [comment]
I'm fine with that, at least ot get something up there.

**Comment by rbbeeston** [comment]
I need help finding the help on the old site.. I's not anyplace obvious...

**Comment by rbbeeston** [comment]
I've changes the extra "contact"  in another ticket

**Comment by rbbeeston** [comment]
There was no earlier contact page, so it was decided to connect to the mailing list as a contact means for the time being.
Additionally, the footer links for twitter and github were changed to icons, including using the new "X" logo.

**Comment by rbbeeston** [comment]
Going to close this, as the main items have been completed, and create a new low priority issue for the contact issue.
