### ISSUE TITLE
Antora docs header does not align with the non-docs pages

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1227]
site page:
![image](https://github.com/user-attachments/assets/1ff37589-82a0-41c0-a9fc-bc51558c3514)

antora page:
![image](https://github.com/user-attachments/assets/5a251baf-456e-48d6-a3e6-a3fd7155d83a)

**Comment by rbbeeston** [comment]
this was fixed, but has to be adjusted again due to the added wrapper

**Comment by rbbeeston** [comment]
fixed in another ticket
