### ISSUE TITLE
Controls shift horizontally on theme change

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1229]
When switching between light and dark mode, the icons in the top right shift horizontally:

![image](https://github.com/user-attachments/assets/b59f6c85-27be-4c42-9296-747f628077a3)

![image](https://github.com/user-attachments/assets/0b70462d-b331-488d-a7b4-b8bc3da5f51a)

![image](https://github.com/user-attachments/assets/4d36cee9-b18e-4d20-b484-6513a87ec13e)

**Comment by rbbeeston** [comment]
already fixed
