### ISSUE TITLE
Old release downloads are missing

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1231]
Version 1.41.0 has no download links:

![image](https://github.com/user-attachments/assets/6ee1109a-2e40-4086-a44d-98758c95ae8d)

Yet they exist on the old site:

![image](https://github.com/user-attachments/assets/915df39a-5656-4239-8b53-bf021f38a998)

**Comment by sdarwin** [comment]
https://www.stage.boost.cppalliance.org/releases/boost-1-41-0/

Excellent job @GregKaleka !  Fixed. Closing issue.
