### ISSUE TITLE
UX glitches (flashing B, wronlgy sized avatar)

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1267]
This is with Firefox 130.0.1 on Windows:

https://github.com/user-attachments/assets/4ecad7c3-dd1e-41a9-89c3-251a59254b84

* A gigantic B logo flashes before the docs for Array appear
* The user avatar is wrongly sized.

**Comment by rbbeeston** [comment]
@joaquintides are you still seeing these issues? they should be resolved now.

**Comment by joaquintides** [comment]
@rbbeeston nope, it doesn't show anymore, thank you!
