### ISSUE TITLE
Mobile UX omnibus

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1268]
A number of UX problems I detected on my iPhone:

* "Join" wrapping (for some doc formats, not for all):

![imagen](https://github.com/user-attachments/assets/83d36dfc-4b31-4ca0-98c3-aed4bc3a5282)

*  No marging and wrongly placed internal nav arrows (again, for some doc formats only):

![IMG_0079](https://github.com/user-attachments/assets/ab6202f8-ed4b-4b13-93d6-a0722b561531)

* `<code>` elements display with obnoxious background color (for some doc formats only, the example is Unordered):

![imagen](https://github.com/user-attachments/assets/72f22a35-d816-40db-a631-b1cf40abfc33)
![IMG_0081](https://github.com/user-attachments/assets/3194c255-9bd5-4423-bfdd-cc4f7e40fa43)

* Ugly looking footer ((for some doc formats only, the example is Accumulators):

![IMG_0082](https://github.com/user-attachments/assets/141cfbc7-2a36-4e90-88a7-606f4fd4e4af)

**Comment by rbbeeston** [comment]
@joaquintides These should be fixed - although docs formatting/coloring is still in process, and should be managed in individual tickets

**Comment by joaquintides** [comment]
@rbbeeston 

* Join wrapping: OK, although the icons and the "Join" legend appear slightly shifter to the left wrt the libraries section:

![imagen](https://github.com/user-attachments/assets/2668dcb1-b0cb-4d08-9bdb-80d42d4d3fff)


* No marging and wrongly placed internal nav arrows: OK
* `<code>` elements display with obnoxious background color: NOT OK (stays the same, I understand you're managhing this elsewhere)
* Ugly looking footer: OK

**Comment by rbbeeston** [comment]
the join alignment will be addressed separately, that's related to the beautiful soup import, which has other issues at the moment.

and yes, the background color issues are managed in boostlook.

I'm OK to close this.
