### ISSUE TITLE
Boost Release Report -  html page and print as pdf

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1287]
visual improvements and other items to be added

**Comment by vinniefalco** [comment]
The next step here is that we need to design how we want the final report to look and then work backwards to make dreams into reality.

**Comment by rbbeeston** [comment]
General design here:
https://docs.google.com/presentation/d/1oye8ZeJQTOhdsT9MK8T_6IFozB3TK4fl9N6x-1El-Zo/edit#slide=id.g30bf3a59df8_0_15

Let me know if you want to discuss

**Comment by rbbeeston** [comment]
Instead of having a statistic for "open issues"  we would like to replace that with "closed issues & Merged PR's"

However there may be special cases for authors who insist on keeping the "upstream" repo of their contributions outside of boostorg

**Comment by rbbeeston** [comment]
Completed
