### ISSUE TITLE
Which social media should we be linking up? 

### ISSUE THREAD

**Issue by frankwiles** [boostorg/website-v2#130]
![CleanShot 2023-02-27 at 10 11 46](https://user-images.githubusercontent.com/144159/221617558-5bfea1a2-b737-4971-8008-30ac0265f305.png)

Saw these weren't linked anywhere and not sure which Boost even has. 

- [ ] Twitter https://twitter.com/boost_libraries
- [ ] Github

**Comment by gregnewman** [comment]
That's a good question and one we should bring up Friday @frankwiles .  @williln and I had looked on the old Boost site and didn't see any accounts.
