### ISSUE TITLE
db: per-release commits contain everything since last major release

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1327]
When building the per-release per-library commit data, only consider branch names which match the pattern "number dot number dot zero" as releases. When determining what the previous release is, only consider branch names which match the pattern "number dot number dot zero." Alternatively, form the previous release branch name numerically from the current release branch name.

Examples:

master and develop branches will not be considered releases. 

"1.82.1" would not be considered a release

"1.86.0 beta-1" would not be considered a release

When calculating the commits for "1.83.0", the range of commits will run from "1.82.0" to "1.83.0" and not "1.82.1" to "1.83.0"

Note:

When writing this Python code please add comments so the reader understands this algorithm.

**Comment by brianjp93** [comment]
Should the release dropdowns in the library list/detail pages and release pages show only the x.x.0 releases?

**Comment by sdarwin** [comment]
> Should the release dropdowns show only x.x.0

Occasionally they need to release x.x.1 or x.x.2 as a bug fix.   How could that work if it remained x.x.0?

**Comment by vinniefalco** [comment]
The dropdown needs to show those versions. And at some point in the future we might make it a combobox so you can type in the number, because a menu with ~100 items is clumsy af.

**Comment by brianjp93** [comment]
The reason I ask is because we are going to import commit data per x.x.0 release, so if a user selects a x.x.x release, there won't be any commit data directly related to that release.

How should that be handled?  Maybe just show the data for the most recent x.x.0 release?
