### ISSUE TITLE
Updates to avatar appearance

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1330]
some minor UI tweaks to the avatar views:
1. Lighter contributor font, let's do a font-weight of 300
2. "Release Maintainers & Contributors" is too wordy. Open to suggestions...
3. Remove the green from the new contributors, make it like a regular contributor, and change it to  "Contributor - New" as the text.
4. Have the maintainers first, but in the same row as the contributors, but the author should be on a seperate row
5. Even if there is no release update the Author and maintainer should still be displayed if available. let's make the font-weight 400

**Comment by brianjp93** [comment]
Maybe just "Release Contributors" instead of "Maintainers & Contributors"?
