### ISSUE TITLE
change sans-serif references to fonts

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1335]
@vinniefalco would like to see any references to `"Noto Sans", sans-serif` fonts changed to `"Noto Sans", serif` so any cases where the fonts are not displaying correctly would be more obvious.

Requesting a change to have serif in staging and sans-serif in production, so it's obvious in staging if the fonts aren't loading and has a gentle fallback in production.

Additionally, add `display:swap` to the font-face tags to remove loading delay.

**Comment by gavinwahl** [comment]
we already have `font-display: swap` : https://github.com/boostorg/website-v2/blob/develop/static/css/fonts.css#L7
