### ISSUE TITLE
per-release library boostdep reports

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1336]
Each library should track its own boostdep report per-release. The UI should show when dependencies are added or removed relative to the previous release.

**Comment by vinniefalco** [comment]
These are the current reports:
https://pdimov.github.io/boostdep-report/

**Comment by rbbeeston** [comment]
Which project would this go under?

**Comment by vinniefalco** [comment]
What do you mean which project?

**Comment by rbbeeston** [comment]
additional detail:
For example, a Library page shows contributors sorted descending by commits. While in the release report, the library page not only shows the sorted contributors and also shows the number of actual commits

For boostdep I would like dependency information included on the Library page which compares it to the previous version of the library. And I would like dependency information for the entire release shown on the Release page, compared to the previous release. For example a release might show that a total of 5 libraries reduced the number of dependencies, and only 1 library increased it
