### ISSUE TITLE
Dmitry has an alias

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1338]
Dmitry has an alias in this release:

https://www.stage.boost.cppalliance.org/libraries/json/boost-1-85-0/

**Comment by brianjp93** [comment]
@rbbeeston In the admin, go to the CommitAuthor changelist and search for the 2 authors you would like to merge.  Select them and use the `merge authors` action in the actions dropdown. 
![Image](https://github.com/user-attachments/assets/8fd54324-3d7b-4c7f-a3d6-1718b60be5f9)

**Comment by rbbeeston** [comment]
Completed.

**Comment by vinniefalco** [comment]
Hey that's a pretty cool UI for the admin !!! Did Brian do that?
