### ISSUE TITLE
Contributor reports based on slack interaction

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1367]
since a lot of mailing list activity has moved to slack, we are considering options to create reports based on slack interaction through the API.

This is in its beginning stages, so we are looking for ideas and feedback. 
Consider looking at this part of the api for what kind of data may be available to use:
[https://api.slack.com/admins/audit-logs](https://api.slack.com/admins/audit-logs)

**Comment by gavinwahl** [comment]
We can get message counts per user per day with this endpoint, but it requires a Business+, Select/Compliance, or Grid plan so we can't use it: https://api.slack.com/methods/admin.analytics.getFile
There is another endpoint to get all messages that we could download the entire message history from: https://api.slack.com/messaging/retrieving

**Comment by gavinwahl** [comment]
Is the goal to save aggregate stats for user activity between release cycles as we did for emails?

**Comment by vinniefalco** [comment]
Something like that yes. To note when someone new appears, or when someone stops posting. Who are the top posters, most active channels, and especially we want to track any channel that has the word boost at the beginning.

**Comment by gavinwahl** [comment]
We have an option here: store all message history in our db, or do some aggregation to store less data based on what we want to show. Currently I'm tracking activity into hourly buckets per channel per user

**Comment by gavinwahl** [comment]
We have to have a script to get all message history through the API, which after the first run can be run again on a schedule to get only new messages. However, there is also a webhook that we could use to get notified about new messages as the happen as an optimization if desired. https://api.slack.com/apis/events-api#rate_limiting

**Comment by rbbeeston** [comment]
Rather than storing all messages, would it be enough to perhaps store something simple like a name, date and message count that gets run on a daily basis (we'd need to do some type of previous data import, but I'm looking forward) that would allow us to get users and counts between release dates, or all time without being a heavy lift for the DB.

Since slack messages tend to be more like texts than emails, would we want to measure counts by any message, like "ok", "Sure", or "No" or have a minimum character count?

**Comment by gavinwahl** [comment]
Do we need to store users' slack avatars?

**Comment by sdarwin** [comment]
> The avatars of tens of thousands of slack users?  all users.  

no.  

> A few avatars, for a release report?  

If you determine that is the case please store them in the S3 media bucket along with web-user avatars. Or hyperlinking, if that seems to work well and it's supported.

**Comment by gavinwahl** [comment]
@rbbeeston 
> Since slack messages tend to be more like texts than emails, would we want to measure counts by any message, like "ok", "Sure", or "No" or have a minimum character count?

Let me know what the requirements are.

**Comment by rbbeeston** [comment]
since there was no response to that question, I would assume there wouldn't be any filtering.

**Comment by gavinwahl** [comment]
@brianjp93 you should have what you need now
