### ISSUE TITLE
import boostlook into website-V2

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1370]
We need a process to get boostlook into Website-V2 that will also be updated whenever the boostlook repo is updated, both in stage and production.

we would like to see it appear in the  `/static/css/boostlook.css` directory.

Putting Julio and Sam initially as assignees, but feel free to reassign to whoever makes sense, or helped with getting it into V2-docs 

- [ ] #1371

**Comment by julioest** [comment]
Pulling in the good lad, @alandefreitas - he implemented boostlook into v2-docs

**Comment by alandefreitas** [comment]
The process for v2-docs is implemented directly there. It checks the latest version in boostlook and imports it when building the static pages. I'm not sure there's an equivalent strategy for website-v2. website-v2 might just want to use the file directly from somewhere and boostlook would be responsible to uploading this file to this location.

**Comment by sdarwin** [comment]
There are multiple ways to implement it. 

1. (this should work) When boostlook.css is checked into the `master` branch of https://github.com/boostorg/boostlook, that triggers Github Actions (in the boostlook repo) to remotely check-in the file to the `develop` branch of website-v2.    Such a  commit in the `develop` branch of website-v2 will cause a deployment to staging.   That can be viewed on staging, to test.   Later, a manual merge from develop to master on website-v2 will deploy to production, and it's guaranteed to be what was seen in testing.

2. (not as ideal) When github actions builds any branch of website-v2, it checks out files.   Right after checking out files, it could download a copy of boostlook.  Include that in the deployed container.  The problems are that production and staging might diverge. There is not a guarantee of having tested the same file on stage.   Moreover, an environment on a local developer machine does not run github actions, so this process won't happen to them, and they won't get the latest boostlook.  To fix that, when container builds happen, it could conceivably always "download" boostlook. There is less assurance the same file exists everywhere.  

the first option above should not be difficult.  requires a token in github secrets.

**Comment by julioest** [comment]
I've tested the workflow on my forks as suggested. You can check out the boostlook workflow file here: [update-website-v2.yml](https://github.com/julioest/boostlook/blob/master/.github/workflows/update-website-v2.yml). And here's the [import commit](https://github.com/julioest/website-v2/commit/7343f92588b3530695e65a3774871326550f73b4) from website-v2

**Comment by sdarwin** [comment]
Great! looks correct.

**Comment by julioest** [comment]
Worked successfully during yesterday's merge, closing the issue.
