### ISSUE TITLE
Odditiy in Stringview library Author

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1396]
See image. Looks like the author name is being parsed for some reason. Found in production, not seeing in stage.
![Image](https://github.com/user-attachments/assets/3aebf00d-ab34-4e5e-9200-e6441538ec06)

**Comment by brianjp93** [comment]
@rbbeeston The "update authors & maintainers" button can be retriggered in the library admin.  Once it finishes I think this should be resolved.
