### ISSUE TITLE
Consolidate makefile and justfile into justfile

### ISSUE THREAD

**Issue by daveoconnor** [boostorg/website-v2#1413]
We have a Makefile and a justfile which are redundant, and some of the recipes are broken (e.g. `make pip-compile`). It's a bit of a maintenance problem as well as unclear during onboarding which is to be used.

This should be merged into one justfile and the commands tested (where possible).
Documentation should be updated to reflect the changes.

**Comment by gavinwahl** [comment]
👍 I was confused by this
