### ISSUE TITLE
ValidateGitImages is buggy

### ISSUE THREAD

**Issue by gavinwahl** [boostorg/website-v2#1438]
in [`libraries/detail.html`](https://github.com/boostorg/website-v2/commit/06b9568a829196#diff-75ea1beda7a0ad5e17472c31bc63cedd82bde21b535ccef3ff377f59f5fe9190R235), ValidateGitImages index is the index of the image when the document was loaded. Then, onerror removes images from the document, invalidating all existing indexes. This results in the wrong images being removed  when there is more than one broken image on a page.

document.getElementsByTagName returns ["a live HTMLCollection of elements"](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName), meaning its contents change when the document changes and indexes into it can not be used across document modifications.

**Comment by gavinwahl** [comment]
At https://www.stage.boost.cppalliance.org/libraries/algorithm/:

![Image](https://github.com/user-attachments/assets/1bffed1b-0d59-4492-b59c-5d90aa3c24cc)

**Comment by rbbeeston** [comment]
Gavin, you are welcome to take a stab at this. Basically the goal is to remove any broken image icons, Vanilla javascript. If you have a better solution, we'll take it!
