### ISSUE TITLE
Remove reports with no commits in the release report

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1447]
In the Release report there are many libraries mentioned with no commits or updates. There is a desire to remove these from the report.

If others do want to keep that in, perhaps there could just be a list of them on a single page, but at the moment that's not part of this issue.

**Comment by brianjp93** [comment]
@rbbeeston Should it be skipped only if there are no new issues opened/closed AND no commits?  If it has one or the other, it should still be shown?

**Comment by rbbeeston** [comment]
checked with boost-website, and we will assume that we only care about commits. No commits, not listed.

Thanks!
