### ISSUE TITLE
New Logo is Needed

### ISSUE THREAD

**Issue by karolherbst** [boostorg/website-v2#1465]
Like.. it's kinda obvious, ain't it? And sure, probably nobody of you intended this, but like... please don't? I'm sure you don't want to appeal to those kind of people, so I'd rather think this should be sorted out sooner rather than later :)

Or if you really really think this is a good idea to go ahead with the current logo, you should at least be kinda aware of how this can be interpreted and the implications of doing so :)

Obviously if this goes live as is and replaces the current website, anybody proposing adding boost as a dependency in upstream projects would immediately raise a red flag. And I'm not available for any of the "please keep politics out of tech" nonsense either, before anybody here gets any ideas.

So _please_ consider carefully here.

![Image](https://github.com/user-attachments/assets/5e588ab9-100a-49c5-997b-53c35d658b48)

https://en.wikipedia.org/wiki/Schutzstaffel

https://www.adl.org/resources/hate-symbol/ss-bolts

![Image](https://github.com/user-attachments/assets/b16a9330-2970-4190-acae-093de1ecb571)

**Comment by vinniefalco** [comment]
You are right that it was not intended, and do note that this was produced by https://grainandmortar.com/ a couple of years ago. We are exploring alternatives, and thank you for bringing this to our attention.

**Comment by mikedekay** [comment]
Thank you for bringing us to our attention. It was certainly not our intention to create a mark that resembled a hate symbol and we are working with Boost on a new design.

**Comment by zachleat** [comment]
Love y’all at Grain and Mortar (hello from Omaha). Glad to see it was just a mistake and hope you ship a fix soon!

(I’d recommend y’all close this issue to public comments to avoid a pile-on)

**Comment by vinniefalco** [comment]
Locking is possible, although maybe a discussion about a suitable replacement could take place? We would love to hear feedback on some new potential logos, or if you have your own ideas those are cool too. A hexagon and the letter "B" seem to be resonating the most, internally:

![Image](https://github.com/user-attachments/assets/f15c7090-352f-465b-a47e-4c282866c5bc)

**Comment by zachleat** [comment]
Fair enough! Love that bottom right one and the one above it! Really evokes a feeling of a rocket boost

**Comment by vinniefalco** [comment]
> Really evokes a feeling of a rocket boost

Yes! That is what the artist was going for. I was hoping to have a more distinct vertical stem though, because the stripes do weaken the shape of the letter. I came up with this:

![Image](https://github.com/user-attachments/assets/ab6d284a-9a07-4063-a8de-a36009bcf33a)

What else might we try?

**Comment by vinniefalco** [comment]
![Image](https://github.com/user-attachments/assets/9b347c43-ab08-478d-a7a9-c4f50c6b3d47)

**Comment by vinniefalco** [comment]
I don't think we need to worry about resemblance to the Bitcoin logo since these are in two different categories. The reality is that a "stylized B" logo is rather common and there will be some resemblance to other brand icons which is unavoidable. Fortunately the domain of cryptocurrency is sufficiently different from the domain of open-source C++ libraries that potential resemblance will be practically unremarkable.

**Comment by vinniefalco** [comment]
We will have to do something with this 

<img width="362" height="417" alt="Image" src="https://github.com/user-attachments/assets/17125be5-d53c-4e4a-a11e-a056bc81ee39" />

**Comment by rbbeeston** [comment]
do you have a jeweler I should assign that to?
