### ISSUE TITLE
Add placeholder image to report cover

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1467]
we would like the below image on the cover. It would be best if the image could have a name that would match the release, like "1-87.png" or something like that, so it could be placed or loaded easily in the future.

![Image](https://github.com/user-attachments/assets/9a9189c1-1436-423b-81b5-367900dfd242)

**Comment by brianjp93** [comment]
Will this be a different image for every release?
Maybe this should be a staff-uploadable image in the Version model admin?  The Version model could have a `release_report_cover_image` field.

**Comment by rbbeeston** [comment]
Yes, it would be different for each release, I think that would be a good idea. Run with that!

**Comment by brianjp93** [comment]
The version holds the image which will be used on the release report.

To set/update an image to be used for the 1.86.0 release report for example
- go to the version admin `/versions/version` and select the row for 1.86.0.
- upload an image to the `release_report_cover_image` field
- re-generate the release report in the library admin
