### ISSUE TITLE
remove old new logo

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1485]
We should remove the old new logo from the site, in the top left corner, in the artwork on the homepage, and in the Logo Usage Policy. Plus, anywhere else that it appears. This way if we want to go live we can do so without additional work. And we can continue to develop new logo ideas for eventual placement on the site after approval.

**Comment by GregKaleka** [comment]
> Logo Usage Policy

Where is this, exactly?

**Comment by vinniefalco** [comment]
https://www.boost.io/doc/contributor-guide/docs/logo-policy-media-guide.html
