### ISSUE TITLE
counts seem off on Release Reports

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1506]
note that there are commits, but no line changes?
![Image](https://github.com/user-attachments/assets/37654677-9d76-44c7-821f-cf2653f6e88b)

**Comment by brianjp93** [comment]
@rbbeeston Those update lines are part of the commit update task.  But it was added after the initial import was done.  I'm guessing that all that needs to be done is to re-run the commit update import.  That can be done in the commit admin.

**Comment by rbbeeston** [comment]
I tried running a new one after following your instructions, still seeing the same issue. 

[Boost 1.86 release report - 12-3-24.pdf](https://github.com/user-attachments/files/18003960/Boost.1.86.release.report.-.12-3-24.pdf)

**Comment by rbbeeston** [comment]
fixed in other tickets
