### ISSUE TITLE
Add periodic tasks for updating release report data

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1519]
Add periodic tasks that update release report utilized data that updates the versions, commit updates, contributors , mailing lists, issues and mailing list data (and anything else that's needed, except the slack reports, as they are updated daily) so that everything is current without having to click each button manually.

**Comment by brianjp93** [comment]
After discussing, this will be a manually run "supertask" rather than many periodic tasks.  For many of these tasks, it is not useful to run them frequently.  They just need to be run after a release.
