### ISSUE TITLE
allow user to select between google accounts on login

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1536]
allow user to select which google account to log in with, rather than defaulting to whatever the users is logged in currently as

**Comment by sdarwin** [comment]
When I try either Login or Sign-up, in both those cases, Google already shows me a screen that says:

Choose an account

With multiple choices...

Do you not see that option?

**Comment by rbbeeston** [comment]
@sdarwin you get this behaviour if you haven't already logged in with an account in that browser. If you have already logged in, it doesn't ask you what account you would like to use, and just sends you an email. It's rather confusing if you don't know what's happening. Most websites will ask as a default, and it's a minor settings fix.

**Comment by sdarwin** [comment]
Hmm, ok.  The behavior I described above happens in these cases:  
- You are already logged into multiple gmail accounts
- You are not logged into any accounts

The issue you are solving occurs when:  
- You are logged into only one account.

If it's just a minor settings adjustment, that makes sense.
