### ISSUE TITLE
Light/Dark mode dropdown needs "System" setting

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#313]
We need the 3rd menu item to explicitly set "inherit from system"

**Comment by gregnewman** [comment]
I can do that but I have it configured by default to inherit from system.
I think that’s less confusing

**Comment by vinniefalco** [comment]
Its fine to default to inherit, but if the user then changes to "Light Mode" (meaning, light mode regardless of system setting) they need a way to change it back to inherit.

**Comment by rbbeeston** [comment]
Managed automatically, no longer needed
