### ISSUE TITLE
Numeric Conversion documentation link goes to wrong URL 

### ISSUE THREAD

**Issue by glenfe** [boostorg/website-v2#318]
It goes to https://www.boost.org/doc/libs/1_82_0/libs/numeric-conversion/ which is 404

It should go to https://www.boost.org/doc/libs/1_82_0/libs/numeric/conversion

**Comment by vinniefalco** [comment]
Yep that's one of the "special cases" libraries. We really should try to normalize that if possible.

**Comment by GregKaleka** [comment]
This seems like it may have been resolved?!

[Image](https://github.com/user-attachments/assets/934b3c86-0cf8-4e1c-9e56-d0ee70a32800)

**Comment by rbbeeston** [comment]
appears to be working fine.
