### ISSUE TITLE
Style Guide needs Light Mode Update

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#364]
The Boost Style Guide document needs a light mode section. We might need to get the original document from Grain & Mortar. If it is a figma thing then we will need to ask them to convert it to a Google Slides document (can that export as PDF?). Or we will have to do it ourselves.

@novoio to address the issue and @gregnewman to provide guidance (if possible).

**Comment by vinniefalco** [comment]
Actually we should probably use Asciidoc and make it a loose page in site-docs for now.

**Comment by rbbeeston** [comment]
This is outdated, and a new ticket will be created when appropriate
