### ISSUE TITLE
UI Updates for Library Detail Page

### ISSUE THREAD

**Issue by d-spencer-strickland** [boostorg/website-v2#535]
- Header should be made to be consistent.  We should figure out how to handle this:
  - <img width="991" alt="image" src="https://github.com/cppalliance/temp-site/assets/49487079/c725f2a7-dd07-4c2e-8492-75d22f284e80">
  - <img width="991" alt="image" src="https://github.com/cppalliance/temp-site/assets/49487079/e7d3b4b2-075d-48c1-8133-10b7771ab258">
  - We're using the mustard currently to be Card Headers (see Community, Learn).  Page headers (on Releases, and now there is one per Library Listing page below the filters [felt like it belonged after the filters though by purely design standards I wanted to put it above.. but was going to wait for feedback]) are using the basic White/Slate text color.
  - To be consistent I believe the library name should not be in mustard, but instead in the White/Slate.  I think it will look better anyways because the Mustard doesn't look as good set on the light mode background IMO.

- Left panel redesigned to match changes from Releases
  - Includes overall spacing/alignment issues with text and with icons, removal of document icon, etc.

- apexchart

- Drop-down for version should match the new style in Libraries

**Comment by vinniefalco** [comment]
if the library name is not mustard can we at least try putting it in bold, because it doesn't look special anymore
