### ISSUE TITLE
Color / text & other element styling issues across sections

### ISSUE THREAD

**Issue by d-spencer-strickland** [boostorg/website-v2#558]
Drop-downs 
- the color of the text should match the placeholder text in the on-page Search input text field.  All drop-downs.  
- hover effect should not be a text color change but perhaps something slight with the border/ring
- option values should not have any special color. not happening on my environment, but it's happening, and needs to go away.
- make drop-down extend down when it has enough elements to use up more of the page height (lower priority)

Icons (on Libraries specifically, but some likely applies to buttons w/icons such as on News) 
- Light: the background of the selected icon should match the background of the other elements (which is simply bg-white)
- Outline of the icons should be same outline (border) used for the neighboring form elements
- The rounded corners on icons should match with the neighboring form elements
- Color of the icons themselves should be white/slate for dark/light

Re-order Library icons to be Grid, By Name, By Cat.

In Library Listings - library name always mustard bold, on By Category remove the bold from category name

Library Detail - POSSIBLY try making the library title in Bold, but this is more of a test.  (don't want to make it drastically different from the title element on Releases/Library Listings - so perhaps they all could settle on a semi-bold to split the difference, will test)

Releases - top of the card is too close to the title.  Compare spacing between title and next page element between pages.

In Header - LEAVE the Join link in the current colors but everything else goes back to before.  (though the sun/moon should not have their original color and instead match the other icons)

**Comment by 4down** [comment]
#565 addresses the Header items
