### ISSUE TITLE
Use official documentation

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/website-v2#559]
## Context

The official boost documentation is built by a [CI script](https://github.com/boostorg/boost/blob/master/.circleci/config.yml) in [boostorg/boost](https://github.com/boostorg/boost) that runs a [python script](https://github.com/boostorg/release-tools/blob/develop/ci_boost_release.py) in [boostorg/release-tools](https://github.com/boostorg/release-tools). The result of this process is what goes to https://www.boost.org/.

However, when initially discussing ideas for the new website, we had an idea for another release script that would (i) bypass the [`b2`](https://www.bfgroup.xyz/b2/) build system boost uses for the documentation if a repository is "antora-enabled" with an antora docs folder, and (ii) build other release variants users have been asking for [^1]. This [second release script](https://github.com/cppalliance/boost/blob/master/release/ci_boost_release.py) is implemented in [cppalliance/boost](https://github.com/cppalliance/boost), which also has a job to upload the results to an AWS bucket, and is what the temp-site is effectively using. 

This second process also includes a patched version of some libraries where the real documentation is replaced with Antora-enabled documentation. So some documentations on the current website are not the real documentation.

## The problem

As both projects become more mature and one might get to the finish line before the other, we have to decouple these things as they are independent proposals to the community. `temp-site` should use the real documentation and the changes to the release process should be proposed directly to [boostorg/release-tools](https://github.com/boostorg/release-tools). 

In this process, the changes to the release process will go to repositories that are not directly under our control. There will be no place to upload the files to the bucket from. We can try to approve yet another proposal to make this happen directly from [boostorg/release-tools](https://github.com/boostorg/release-tools) *or* we will need a job directly on the `temp-site` repository that periodically builds and uploads the documentation itself.

## Summary

Details apart on how to do this, this is what is actionable in this issue:

1) We should propose our changes to the release process to `boostorg/release-tools`
2) `temp-site` should use the official docs generated by `boostorg/release-tools`

[^1]: legacy-release for compatibility, docs-only release for the website, source-only release for users and CI, and cmake-release to replace the alternative releases generated by [a different script](https://github.com/boostorg/boost/blob/master/.github/workflows/release.yml) many users are effectively using

**Comment by sdarwin** [comment]
Specifically about "develop" and "master" docs, boost.org is hosting them at:  
https://www.boost.org/doc/libs/develop/
https://www.boost.org/doc/libs/master/

temp-site uses similar URLs from the S3 bucket address and then /archives/develop or /archives/master

These are updated, or should be updated, when release-tools runs and builds a new archive.  Not at other times.  

release-tools itself could upload these docs to S3.  

I will work on adding that in release-tools.  "develop" and "master" documentation, not anything else (such as archives in general, or site-docs, etc.)

**Comment by rbbeeston** [comment]
@alandefreitas is this still under consideration, or has the site moved past it?

**Comment by alandefreitas** [comment]
The only issue left here was "temp-site (now boostorg/website-v2) should use the official docs generated by boostorg/release-tools".

I'm under the impression this is already happening (because whatever I change in website-v2-docs eventually ends up on the website). 

But I can't confirm how or where this happens because I don't understand the website-v2 codebase and all procedures in place uploading to AWS buckets. Sam understands the process in more detail.

**Comment by sdarwin** [comment]
> whatever I change in website-v2-docs eventually ends up on the website.

GHA on the website-v2-docs repo uploads to S3.  

From there, Django shows it on boost.io.

> boostorg/website-v2 should use the official docs generated by boostorg/release-tools.

`release-tools/publish_release.py`, every 3-4 months when a release is created, uploads a copy of the extracted docs to S3. Django uses that on boost.io.

**Comment by alandefreitas** [comment]
I think this issue is solved, then
