### ISSUE TITLE
Add command to import Sourceforge links for Boost versions older than 1.63.0

### ISSUE THREAD

**Issue by williln** [boostorg/website-v2#584]
Starting with 1.63.0, Boost started using Artifactory to host its downloads. Before then, it used Sourceforge. https://sourceforge.net/projects/boost/files/boost/ 

Add a command to import the Sourceforge links. Will likely be similar to https://github.com/cppalliance/temp-site/commit/faa74781215b67998413948595a3e5241885c518 

Raised from https://github.com/cppalliance/temp-site/issues/493

**Comment by williln** [comment]
@4down We don't currently have any of the Sourceforge downloads (downloads for versions older than 1.63). Do those need to be in place before Dec. 16?

**Comment by rbbeeston** [comment]
@vinniefalco is this still outstanding?

**Comment by sdarwin** [comment]
@rbbeeston see https://github.com/boostorg/website-v2/issues/1230 .  

After that ticket is completed, return to this issue, and re-import releases.  Check that the import code isn't stopping at 1.63.0,  but will be able to continue to the earliest available files that are now hosted on archives.boost.io. Nothing will need to be done with sourceforge links in that case.

**Comment by vinniefalco** [comment]
I have no idea what this is about

**Comment by sdarwin** [comment]
Imported sourceforge files to AWS S3. Completed.
