### ISSUE TITLE
Library documentation with iframes

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#621]
Three libraries are using the "frame" html tag, and temp-site will not display the page. Might not be critical, but it does affect those Boost library docs:
https://www.boost.revsys.dev/doc/libs/boost_1_82_0/libs/preprocessor/doc/index.html
https://www.boost.revsys.dev/doc/libs/boost_1_82_0/libs/serialization/doc/index.html
https://www.boost.revsys.dev/doc/libs/boost_1_82_0/libs/iostreams/doc/index.html

**Comment by sdarwin** [comment]
A solution can be to have a list of exceptions [ "preprocessor", "serialization", "iostream" ] and for only those libraries open the docs in another browser tab without any extra headers so it's just the original source code.  

I have contacted those libraries and opened an issue. They should modify their doc format in some way or another to remove `<frame>`.     Or, if we know a way to do that, submit a pull request directly to the other repos.

**Comment by sdarwin** [comment]
These three library docs are still not loading.  Possibly submit updates directly to those boost repos, modifying their html.

https://www.preview.boost.org/doc/libs/boost_1_82_0/libs/preprocessor/doc/index.html
https://www.preview.boost.org/doc/libs/boost_1_82_0/libs/serialization/doc/index.html
https://www.preview.boost.org/doc/libs/boost_1_82_0/libs/iostreams/doc/index.html

**Comment by sdarwin** [comment]
If they can't be fixed.. open the 3 libraries docs in another browser tab, and just display whatever they include such as frames.

**Comment by kennethreitz** [comment]
Added some fixes for this today, which can be seen here: https://www.stage.boost.cppalliance.org/doc/libs/1_84_0/libs/iostreams/doc/index.html

1. Allow frame loading from same origin.
2. if the doc request is coming from an iframe/frame, skip "modernizing" the page
3. this leaves us with old branding, but we can improve that component later. These iframe-driven doc sites now are working well on staging.

**Comment by kennethreitz** [comment]
Currently looking into what's going on on these pages: https://www.stage.boost.cppalliance.org/doc/libs/boost_1_82_0/libs/preprocessor/doc/index.html

**Comment by joaquintides** [comment]
This gets us on par with boost.org, but I wonder if we could still get the header somehow. Opening a low priroity issue for that.

**Comment by rbbeeston** [comment]
One note, I suspect this may be due to `<frameset>` being deprecated. That's a commonality all three have, and would make sense to describe the bug.

Ultimately all three of these libraries' documents should be updated to current standards. @grisumbras these should perhaps be prioritized for updates
