### ISSUE TITLE
Boost site docs does not default to the same theme as the website

### ISSUE THREAD

**Issue by mborland** [boostorg/website-v2#678]
My system default is dark mode, so when I open https://www.preview.boost.org it defaults to dark mode as it should. When you click on the question mark button in the top right corner the you are sent to: https://www.preview.boost.org/doc/user-guide/intro.html. Once this page loads it is mostly in light mode, but with some dark mode elements. The text on the left panel looks to be rendering as though it is dark mode making it nearly impossible to read.

System:
Safari 17.0 running on MacOS Sonoma (14.0)  
<img width="2672" alt="Screenshot 2023-09-29 at 9 00 52 AM" src="https://github.com/cppalliance/temp-site/assets/3745830/4a6d5db3-190c-47aa-95a6-dd35f409329a">

**Comment by rbbeeston** [comment]
Closing as this is being addressed in other tickets, and is mostly resolved.
