### ISSUE TITLE
Change the fallback URL behavior for the static content 

### ISSUE THREAD

**Issue by williln** [boostorg/website-v2#724]
Broken off from #714 

Per @4down: 

> It looks like we have a fallback URL path for any adocs under site-docs that aren't explicitly mapped to their own URL but I can't get those to work on revsys staging. ie, https://github.com/cppalliance/site-docs/blob/develop/site-pages/users/people.adoc looks like it would map to https://www.boost.revsys.dev/doc/users/people/ but that isn't working. This is presumably the same issue as https://github.com/cppalliance/temp-site/issues/1.

> Can we change that fallback URL path to something other than /doc/ - [temp-site/stage_static_config.json](https://github.com/cppalliance/temp-site/blob/704e7d73821b3c6c7ff3856fd0af0843bbaa0939/stage_static_config.json#L35) - since these pages aren't meant to be grouped with the other docs from that repo on the site. `/page/` or `/p/`? Does anyone have a preference or want to leave it as-is?

Per @sdarwin: 

> A proposal is that the fallback URL be removed. Any docs should map to site-pages, site-docs, somewhere in the Django website, or wherever specific content is located. Each group of content should have a mapping. Otherwise display an error such as GitHub's "404 Page not Found This is not the web page you are looking for".

**Comment by 4down** [comment]
I'm not following exactly what is meant by removing the fallback URL.  I feel like if we had a { "site_path": "/page/", "s3_path": "/site-pages/" } that would work fine?  That would mean the explicitly mapped help.adoc would be accessible via /help/, but also using the fallback it could be accessed by /page/help.html

Definitely we need a proper 404 page for something like https://www.boost.revsys.dev/doc/this-page-does-not-exist/

**Comment by williln** [comment]
We have a custom 404 page (see #175), but for some reason it's not working. I've been poking at it for a little bit and I don't know why it's not rendering. I'll keep looking at it.

Let me know how you'd like the fallback URL to be handled!

**Comment by sdarwin** [comment]
That makes sense:

```
{ "site_path": "/page/", "s3_path": "/site-pages/" } 
```

There are multiple problems with the current mapping:

```
  {
    "site_path": "/",
    "s3_path": "/site/develop/"
  }
```

1. The S3 path "/site/develop/" doesn't have content, or a workflow which is populating it with content from a git repo.     It should have actual pages.   Therefore at least map to "/site-pages/", for example.

2. The internet is full of random bots.    If there's a fallback mapping that matches _anything_  such as `"site_path": "/"`, it's sending a lot of traffic to S3 for no reason.    With that in mind, could a visit to the path "/" such as "/this-page-does-not-exist" return a 404?    If the visitor hopes to retrieve a random page from S3, at least require them to add something like "/page/" to the path.      "/this-page-does-not-exist"  could instantly send a 404, not even contact S3, if the last fallback mapping for `"site_path": "/",` was -> 404.

**Comment by williln** [comment]
> With that in mind, could a visit to the path "/" such as "/this-page-does-not-exist" return a 404? 

@sdarwin That is what happens now -- the site returns a 404 when the content isn't found. 

This page in the docs has a reasonable explanation of how we handle urls https://github.com/cppalliance/temp-site/blob/develop/docs/static_content.md but I'll summarize here: Anytime we get a url request, first we try to match it to one of "our" pages -- the Django pages. The patterns are matched in this order: https://github.com/cppalliance/temp-site/blob/develop/config/urls.py#L71 

The very last patterns start here and are the ones that are concerned with retrieving static content from S3: https://github.com/cppalliance/temp-site/blob/develop/config/urls.py#L249  

```python
        # Libraries docs, some HTML parts are re-written
        re_path(
            r"^doc/libs/(?P<content_path>.+)/?",
            DocLibsTemplateView.as_view(),
            name="docs-libs-page",
        ),
        # TODO: Greg - determine correct route for user-guide
        re_path(
            r"^doc/(?P<content_path>.+)/?",
            UserGuideTemplateView.as_view(),
            name="docs-user-guide",
        ),
        # Markdown content
        re_path(
            r"^markdown/(?P<content_path>.+)/?",
            MarkdownTemplateView.as_view(),
            name="markdown-page",
        ),
        # Static content
        re_path(
            r"^(?P<content_path>.+)/?",
            StaticContentTemplateView.as_view(),
            name="static-content-page",
        ),
    ]
)
```

Most of the logic in these views is either in this class, or is in a view that inherits from it: https://github.com/cppalliance/temp-site/blob/develop/core/views.py#L147, and it raises a 404 if the content is not found in s3. But it doesn't cache that 404 response. 

`/doc/lib/` and `/doc/` both do some work in their views to manually set the S3 path (see https://github.com/cppalliance/temp-site/blob/develop/core/views.py#L302)  

```python
class DocLibsTemplateView(StaticContentTemplateView):
    # possible library versions are: boost_1_53_0_beta1, 1_82_0, 1_55_0b1
    boost_lib_path_re = re.compile(r"^(boost_){0,1}([0-9_]*[0-9]+[^/]*)/(.*)")

    def get_from_s3(self, content_path):
        # perform URL matching/mapping, perhaps extract the version from content_path
        matches = self.boost_lib_path_re.match(content_path)
        if matches:
            groups = matches.groups()
            if groups and not groups[0]:
                content_path = f"boost_{content_path}"

        legacy_url = f"/archives/{content_path}"
        return super().get_from_s3(legacy_url)
```

## Notes 

- [ ] We could cache the 404 response, to prevent someone from being able to hammer the site with an invalid path (like `/doc/libs/does/not/exist`) over and over 
- [ ] @4down mentioned preferring handling the paths in the `urls.py` over the static config file -- using the `DocLibsTemplateView` as prior art, if we knew which buckets, or directories within buckets, that we wanted to point to, there is nothing stopping us from adding a url pattern that points to a custom view that then injects the S3 path from a setting, or a config file, or a constant, etc. 
- [x] I opened https://github.com/cppalliance/temp-site/pull/727 to fix why our 404 page wasn't rendering.

**Comment by 4down** [comment]
Note that I added the mapping for "/page" -> site-pages but have not removed any mappings.  Removing the mapping of "/" is something that we might still want to do.  

I wanted to get this mapping in place to begin testing on staging.

**Comment by williln** [comment]
@4down Are we getting rid of the "/" fallback url? If so, what are some good URLs to test with to make sure that that doesn't have any unintended consequences?

**Comment by sdarwin** [comment]
Opened PR 1059 about this ticket.

**Comment by sdarwin** [comment]
Closed with PR 1059.
