### ISSUE TITLE
Docs Header - Alignment of Boost Logo

### ISSUE THREAD

**Issue by d-spencer-strickland** [boostorg/website-v2#733]
The logo is misaligned on both staging and prod, both when logged in and out, when on this URL:  

https://www.stage.boost.cppalliance.org/doc/libs/boost_1_83_0/
https://www.preview.boost.org/doc/libs/boost_1_83_0/

On this URL, it doesn't happen (the header seems different in other ways on this page):

https://www.stage.boost.cppalliance.org/doc/user-guide/intro.html
https://www.preview.boost.org/doc/user-guide/intro.html

@gregnewman It looks like it might just be that the header on libs docs is still using an older version of the header?

**Comment by gregnewman** [comment]
I know what's causing this @4down , I'll tackle this.

**Comment by rbbeeston** [comment]
no longer relevant
