### ISSUE TITLE
Search button disappears in mobile view 

### ISSUE THREAD

**Issue by ashtum** [boostorg/website-v2#740]
![Screenshot from 2023-10-21 14-09-13](https://github.com/cppalliance/temp-site/assets/11743154/98d45389-27fe-4b67-9c52-e64237da797a)

**Comment by ashtum** [comment]
It seems that we are using a completely different button set for the mobile view instead of hiding the unnecessary ones. Since Boost-Gecko finds the search button by its id, we can't have two buttons on the page.

**Comment by gregnewman** [comment]
Yes. It’s a little more complicated than just hiding and showing. The mobile layout is different. I can make it work. Let it be hidden on mobile for now. When you merge to develop I’ll fix the mobile side.

**Comment by joaquintides** [comment]
Fixed by #1077
