### ISSUE TITLE
Page Not Found in library's root directory

### ISSUE THREAD

**Issue by ashtum** [boostorg/website-v2#743]
In the root directory of every Boost library, you can find an "index.html" file that redirects users to the documentation. For instance: https://github.com/boostorg/beast/blob/develop/index.html

When you visit https://www.boost.org/doc/libs/1_83_0/libs/beast, it correctly redirects you. However, on the new website, https://www.stage.boost.cppalliance.org/doc/libs/1_83_0/libs/beast, leads to a 404 error.

**Comment by sdarwin** [comment]
You are pointing out, that the following hyperlink fails:

https://www.stage.boost.cppalliance.org/doc/libs/1_83_0/libs/beast

adding a trailing slash fixes it

https://www.stage.boost.cppalliance.org/doc/libs/1_83_0/libs/beast/

**Comment by sdarwin** [comment]
Consider what nginx does on a basic server:

```
try_files $uri $uri/ =404;
```

First it "tries" the basic filename, which might be a file that doesn't have an extension.  If that succeeds, great.   Next, it tries adding a slash.    

We have to see if that can work in conjunction with `proxy_pass`. 

It might be as simple as adding `try_files` to the nginx config.
