### ISSUE TITLE
Different version listing in Libraries dropdown vs Releases dropdown

### ISSUE THREAD

**Issue by 4down** [boostorg/website-v2#748]
On https://www.stage.boost.cppalliance.org/releases/ and https://www.stage.boost.cppalliance.org/libraries/, there is a difference in the versions that are included in the dropdowns. 

The difference that I notice easily is that 1.25.1-bgl is in the Releases dropdown.  Not sure if there may be other differences that aren't so easily spotted.

Is there a reason for the difference, and if not, which one should we treat as correct (and make sure the other is matched up with it)? 

![image](https://github.com/cppalliance/temp-site/assets/49487079/d1526314-e3a7-4cb5-b8d0-671e5a654f75)

**Comment by joaquintides** [comment]
Can't reproduce (2024/04/06), "boost-1-25-1-bgl" appears on both lists.

**Comment by joaquintides** [comment]
Can't reproduce (2024/04/06), "boost-1-25-1-bgl" appears on both lists.
