### ISSUE TITLE
URLs that need to match between old site and new site

### ISSUE THREAD

**Issue by d-spencer-strickland** [boostorg/website-v2#749]
We need to know definitively which URLs from the old site must remain the same at the new site.  Is it strictly the documentation pages - for libraries - or does it extend to more, or all?

For instance, does https://www.boost.org/users/people.html need to have that same URL post-switchover?

**Comment by glenfe** [comment]
I think it's OK for the URLs to be different, but we could still use redirect pages (or HTTP server redirects) to ensure the old URLs take people to the new ones, right?

**Comment by vinniefalco** [comment]
> we could still use redirect pages (or HTTP server redirects) to ensure the old URLs take people to the new ones, right?

What's the point of that? If we are going through the trouble of setting up redirects then we could just as easily preserve the URLs, and skip the redirect.
