### ISSUE TITLE
The documentation page for libraries changes the style of the navbar.

### ISSUE THREAD

**Issue by ashtum** [boostorg/website-v2#801]
Compare the navbar on a library documentation page with other pages. The best way to compare them is by opening two tabs and switching between them:

https://www.preview.boost.org/libraries/
![Screenshot from 2023-11-03 11-13-07](https://github.com/cppalliance/temp-site/assets/11743154/33f88da0-84c5-47ea-9809-b8e8503a2eae)

https://www.preview.boost.org/doc/libs/boost_1_83_0/doc/html/accumulators.html
![Screenshot from 2023-11-03 11-13-02](https://github.com/cppalliance/temp-site/assets/11743154/75287e7d-c9e6-402a-8d6e-491f4e2f12d5)

This even has an effect on search box fonts; it appears to override the font families of all elements:

![Screenshot from 2023-11-03 11-18-35](https://github.com/cppalliance/temp-site/assets/11743154/8303f0b7-0845-4a1f-b855-95ec7d45d2e6)
![Screenshot from 2023-11-03 11-18-31](https://github.com/cppalliance/temp-site/assets/11743154/10bfad67-679e-4223-b77e-d365e8bf6a78)

**Comment by rbbeeston** [comment]
no longer an issue
