### ISSUE TITLE
Make current-boost-version dynamic for boost-gecko in site header

### ISSUE THREAD

**Issue by d-spencer-strickland** [boostorg/website-v2#844]
The current-boost-version is hardcoded right now at https://github.com/cppalliance/temp-site/blob/6732add8f159b6494a74567f160e671a9f5f663c/templates/includes/_header.html#L32C42-L32C42

```html
<i id="gecko-search-button" data-current-boost-version="1_83_0" ...></i>
```

This attribute should be populated with what the site code has determined is the current release, using the same format.

@ashtum

**Comment by 4down** [comment]
@williln You're probably the best for this, but if not, let me know. Thanks!
