### ISSUE TITLE
Library search bar size inconsistent with adjacent elements

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#933]
https://www.preview.boost.org/libraries/

Library search bar is noticeably taller than the adjacent buttons:

![Screenshot_20240213_000656](https://github.com/cppalliance/temp-site/assets/1589747/d0f0f11e-c421-46aa-86be-5381040d98ef)

**Comment by sdarwin** [comment]
Which browser?  
It looks correct in Chrome, and taller in Firefox.

**Comment by Lastique** [comment]
Firefox 122.0.1, Kubuntu 22.04.

**Comment by mborland** [comment]
Same issue with Safari 17.3.1 on macOS 14.3.1

<img width="734" alt="Screenshot 2024-02-13 at 8 15 12 AM" src="https://github.com/cppalliance/temp-site/assets/3745830/f920763e-1c22-4c7b-a42f-13d276580190">

**Comment by rbbeeston** [comment]
Closing, search box no longer exists
