### ISSUE TITLE
Links in README.md files are not color-coded

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#939]
https://www.preview.boost.org/libraries/atomic/boost-1-84-0/

In the rendered README.md files, links are not colored as such and rendered like regular text:

![Screenshot_20240213_005949](https://github.com/cppalliance/temp-site/assets/1589747/3ebef2ef-5a9d-4c98-ba4b-ba2c46f772e0)

In this example, under "More information", the words "Documentation", "Report bugs", "pull requests" and "Boost Software License, Version 1.0" are actually links, yet this is not visible to the viewer.

Links are color-coded on other pages, such as library documentation and Release Notes.

The original readme in this example is [here](https://github.com/boostorg/atomic).

**Comment by vinniefalco** [comment]
Yes the style sheets for asciidoc/markdown files needs a complete overhaul

**Comment by julioest** [comment]
Looking into this issue
