### ISSUE TITLE
Clicking on library docs links shows redirection page briefly

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#940]
https://www.preview.boost.org/libraries/atomic/boost-1-84-0/

When I click on the Documentation [link](https://www.preview.boost.org/doc/libs/boost_1_84_0/libs/atomic/index.html) on the above page, I can see the automatic redirection page. After that, in a little less than a second, I get redirected to the actual documentation.

This does not happen when I click on the [Atomic](https://www.boost.org/doc/libs/1_84_0/libs/atomic/) library in the old website here:

https://www.boost.org/doc/libs/1_84_0/

or the [Documentation](https://www.boost.org/libs/atomic) link on the README.md page on GitHub here:

https://github.com/boostorg/atomic

In both cases I can immediately see the library docs without the redirection page.

I suspect this may be because the new website takes longer to load, so the redirection page manages to get rendered while the actual docs are being loaded.

**Comment by vinniefalco** [comment]
...or is this because the redirect is going to a different domain? Frank?
