### ISSUE TITLE
Broken link for library category on the library page

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#944]
https://www.preview.boost.org/libraries/atomic/boost-1-84-0/

At the top of this page, it says "Category: [Concurrent](https://www.preview.boost.org/libraries/?category=%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20concurrent&version=boost-1-84-0)". The "Concurrent" link is broken, clicking it shows 500 error. Note that the link contains a number of spaces.

**Comment by kennethreitz** [comment]
I fixed this yesterday! :sparkles: :cake: :sparkles:

**Comment by kennethreitz** [comment]
Note that it is only deployed to staging at this time.
