### ISSUE TITLE
Inline links broken in RSS feed for Boost News

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#946]
https://www.preview.boost.org/feed/news.rss

For most News entries in the RSS feed, the content duplicates the news title, which makes the feed useless. For example, these entries have this issue:

- Johan Berg: Building libraries on top of Boost.Asio
- Mohammad's Q4 2023 Update
- Dmitry's Q4 2023 Update
- Joaquín's Update on Boost.Unordered Evolution

For some entries, there's no actual text but a single non-clickable link:

- Matt's Mathematical Library Updates
- Sam's Q4 2023 Update
- Christian's Q4 2023 Update

In general, all links in this RSS feed are not clickable.

**Comment by kennethreitz** [comment]
Keeping this open to work on inline links as well.

**Comment by kennethreitz** [comment]
Okay, this feed should be much better: https://www.stage.boost.cppalliance.org/feed/news.rss
