### ISSUE TITLE
Integrate Boost release schedule into the new website

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#951]
The review schedule is available in the current website here:

https://www.boost.org/development/index.html

It is very useful for planning library development around Boost releases.

**Comment by sdarwin** [comment]
You may like to comment on it further, but there is a "SCHEDULE OF EVENTS" on the homepage of https://www.preview.boost.org/ that's displaying the calendar information and release dates.

**Comment by 4down** [comment]
I have a page to push out that has the review schedule, I'll update/close this issue once I've gotten it out.  Thanks!

**Comment by Lastique** [comment]
Thanks, I didn't notice it was listing future events. At first I thought it was listing past events.

I think the schedule on the current website is more visual though. I would prefer a more calendar-like view, with the ability to select the time span further into the future (beyond the current month).

**Comment by sdarwin** [comment]
> I would prefer a more calendar-like view

https://www.boost.io/calendar/ shows the calendar.    Add links to this page from elsewhere on the website.

**Comment by vinniefalco** [comment]
wow that's quite ugly :) but no worse than the old one.

**Comment by joaquintides** [comment]
@kennethreitz to close this issue, could you link this page ($HOME/calendar) from the homepage? My idea is that here:

![imagen](https://github.com/boostorg/website-v2/assets/3283164/34329b2e-656e-4410-89f7-019c6bf0cd0f)

we could add a link like this:

![imagen](https://github.com/boostorg/website-v2/assets/3283164/ac213628-91e0-48e1-aa29-17007017bbc4)

Thank you!

**Comment by kennethreitz** [comment]
This is surprisingly harder than it sounds :) @julioest is taking a stab at the HTML portion of this now
