### ISSUE TITLE
Use RSS icon universally on the website

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#955]
Where there are links to the RSS feeds on the website, please use the typical orange RSS feed [icons](https://en.wikipedia.org/wiki/RSS). Preferably, in a consistent place across different pages.

In particular, RSS feeds are mentioned on these pages:

https://www.preview.boost.org/news/   ("RSS" is mentioned as text in the page intro)
https://www.preview.boost.org/releases/  ("RSS Feed" is mentioned as text next to the page title, where the title pertains to a particular Boost release)

In the latter case, it would make more sense to have the RSS icon near Releases at the top bar instead of near the "Newest Release (1.84.0)" title. It doesn't make sense to have an RSS feed that pertains to only one Boost release.

Perhaps, it would be better if the News RSS feed also was near the News entry at the top, as an RSS icon.

**Comment by rbbeeston** [comment]
converted to icon some time ago. As there are planned design changes, the location will be revisited.

**Comment by vinniefalco** [comment]
We need to open a new issue, to analyze our use of RSS and ensure best practices
