### ISSUE TITLE
New site is not compliant with the GDPR

### ISSUE THREAD

**Issue by Julien-Blanc-tgcm** [boostorg/website-v2#960]
The new website is not compliant with the GDPR.

* it stores data in the user browser without user's consent
* there is no "cookie banner", but several trackers are present on the site, which
* it embeds youtube videos, but does not use the youtube-nocookie.com domain to do so
* privacy badger reports several trackers on the page. 

The privacy policy needs some review. It should at least be divided in two :

* what happens when you browse the site (no personal information should be collected imho)
* what happens when you create an account on the site (in which case, personal information can be collected).

**Comment by 4down** [comment]
Resolved by 

- Removing Google Analytics (now Plausible)
- Changing the YouTube Embed on the homepage to an external link to the video 

Thanks!
