### ISSUE TITLE
Profile Setting Option to receive email on material Privacy and Terms changes

### ISSUE THREAD

**Issue by frankwiles** [boostorg/website-v2#986]
Add an option to the user's profile/settings page where they can opt into being notified by email about material (i.e. not just a typo) change to the privacy policy or terms of use. 

This allows human discretion on whether or not to notification is necessary (i.e. if the mailing address changes we don't likely need to spam everyone).  

This also does not complicate the registration process or interrupt site use for the majority of users who likely are not concerned about changes to the policies.

**Comment by GregKaleka** [comment]
@louistatta @rbbeeston, for triggering the email notification, are we OK with a management command that's triggered manually by a dev, or do we want to implement a UI / form for this?

**Comment by rbbeeston** [comment]
This would be a UI form checkbox on the User settings page 
https://www.boost.io/users/me/

**Comment by GregKaleka** [comment]
Yeah I have that part coded up already. But something has to actually trigger the email going out to users who have opted in.

**Comment by rbbeeston** [comment]
I'm wondering, seems like we would need to have a separate page, and when it's changed would trigger it. I would suggest discussing with @sdarwin on how to go about that.

**Comment by sdarwin** [comment]
@GregKaleka   

The actual messages to be sent out:  

There could be a new form in the /admin/ panel, where the text content of the email is entered, and then choices of recipients such as :  

- all registered users  
- all users who have registered for Privacy and TOU updates
- admins

In the short-term however, this ticket can be closed by adding a field in the db to keep track of the setting of who has registered for privacy updates, and that's all.  

Implementing the next part, with a form, is "moderate" priority.  

High priority are:    
1. launch. Can the boost.io website be published on the boost.org domain tomorrow? It's ready to view by the public?  
2. the next boost release very soon, in Dec. boost 1.87.0.  There are reports planned for the 1.87.0 release, and perhaps issues with release notes, other topics.   

discuss with @rbbeeston .    If those 1 and 2 are set, then ok.

**Comment by GregKaleka** [comment]
Got it - I'll put up a PR shortly, then.
