### ISSUE TITLE
How to process a missing trailing slash

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#988]
If a visitor goes to this URL, with a missing trailing slash, it will fail  
https://www.boost.io/doc/libs/1_83_0/libs/json

This works:  
https://www.boost.io/doc/libs/1_83_0/libs/json/

However, that doesn't mean every URL should always get a trailing slash added.   There might be a URL displaying a file called a "Jamfile" in boost, which doesn't have an extension, or a trailing slash.    

- Something should be done in Django or Nginx..

- @ashtum, many Algolia search results for beast go to https://www.boost.io/doc/libs/1_83_0/libs/beast which is missing a trailing slash.  Could that be adjusted in Algolia?

**Comment by ashtum** [comment]
I think this is the same issue as #743.
I believe this should be resolved in the backend side.

**Comment by sdarwin** [comment]
Closing as duplicate
