### ISSUE TITLE
Docs - Some docs come up with blank screen before content appears

### ISSUE THREAD

**Issue by 4down** [boostorg/website-v2#990]
Example:
https://www.boost.io/doc/libs/boost_1_84_0/doc/html/boost_asio/overview/rationale.html

I tried comparing it with one that works and couldn't spot the issue, example of one without the issue:

https://www.boost.io/doc/libs/boost_1_84_0/doc/html/string_algo.html

Possibly due to the additional folders in the path?  

![image](https://github.com/boostorg/website-v2/assets/49487079/40fcdcf3-a784-4801-9b0e-0a34883e8e1d)
_Image shows the problem page on left_

**Comment by joaquintides** [comment]
Can't reproduce it either with Firefox or Chrome on PC. Is this fixed yet?
