### ISSUE TITLE
Docs - Should always have some margins on the page in mobile

### ISSUE THREAD

**Issue by 4down** [boostorg/website-v2#991]
![image](https://github.com/boostorg/website-v2/assets/49487079/c00a7ede-64a9-4e31-9880-82a1c8557924)

Text should not be flush against the sides of the browser.

**Comment by 4down** [comment]
These examples come from 1.84.0, have not checked for the same issue elsewhere but seems like it should be a relatively simple change to the CSS (hopefully at least).

https://www.boost.io/doc/libs/boost_1_84_0/doc/html/string_algo.html

**Comment by kennethreitz** [comment]
Closing in favor of #990, which I believe is the same issue.
