### ISSUE TITLE
Analytics - separate data between staging and prod

### ISSUE THREAD

**Issue by d-spencer-strickland** [boostorg/website-v2#992]
Either we should set up a separate domain in Plausible for tracking staging data and update the code to pass the different domains based on environment, or if Plausible has a way to split the data out via reporting, we could set up reporting to easily see the data for each alone.  The former is probably the better option but we'll decide when we get to it.

Low priority but something that should be done.

**Comment by rbbeeston** [comment]
@sdarwin do we need to differentiate between dev and prod, or just set it up to only record in prod?

**Comment by sdarwin** [comment]
Here are boost.org analytics from the last 30 days.

 ![Image](https://github.com/user-attachments/assets/b71d94f5-ccde-4466-b133-0236da1e7335)

"Plausible excludes bots, crawlers, referrer spam and other known non-human traffic by default."

Traffic on staging will eventually represent a very small percentage compared to production.   Less than 1%.   Therefore, how important is it to remove staging views from the graph?    
I would suggest closing the issue.
