### ISSUE TITLE
State that the website is unofficial

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#993]
As was asked on the Boost ML, please clearly state that the new website is currently *proposed* or *unofficial* until it is accepted as the new official Boost website. Preferably also add a link to the current official Boost website.

This is necessary to avoid confusion on the users' side.

**Comment by vinniefalco** [comment]
Add "Proposed for boost.org"

**Comment by 4down** [comment]
Got it.  

"Proposed for boost.org", with boost.org being a link to the current official site.  Will be done shortly.

**Comment by 4down** [comment]
This has been added to the footer as described in my last comment, and is now live on production.

Thanks!
