### ISSUE TITLE
Add information about library dependencies in a release

### ISSUE THREAD

**Issue by igaztanaga** [boostorg/website-v2#994]
Users adds Boost to their toolset using different approaches when using and installing boost libraries (package managers, adding source to their in-house repos, using their own build system...).

One useful information for users that want to evaluate or limit the size of their boost dependency in their applications is to know the dependency chain of their chosen libraries. This way, users can know and minimize the headers and library compilation requirements that need to be distributed with their applications, SDKs....

Currently [a dependency report] (https://pdimov.github.io/boostdep-report/) is generated for each release in pdimov's website, but it would nice if this information is at least linked in the new website for each release. A nicer dependency report plot or graph generated with the boostdep tool (which produces html, csv, and other formats) would be a nice to have goodie, but the basic information listed in the html report is a good starting point.

**Comment by alandefreitas** [comment]
@PeterTurcan I think we discussed that in some PR in website-v2-docs?

**Comment by PeterTurcan** [comment]
@igaztanaga Agree with your assertions. We can certainly add a link from the User Guide to pdimov's website. I am not sure how a user extracts the full list of primary and secondary dependencies from this report easily - adding an explanation of how to do this to the User Guide would add value. 
@alandefreitas @pdimov

**Comment by alandefreitas** [comment]
> I am not sure how a user extracts the full list of primary and secondary dependencies from this report easily 

There's a list for each library.

**Comment by PeterTurcan** [comment]
OK. Added a short explanation and links in this PR:
https://github.com/boostorg/website-v2-docs/pull/173

**Comment by pdimov** [comment]
Boost should be capitalized.

**Comment by PeterTurcan** [comment]
I can change it, but boost is not capitalized here: https://pdimov.github.io/boostdep-report/
Ideally link text and the target should match - though happy to change it if there is a reason for the lower case on your reports?

**Comment by pdimov** [comment]
I'm emulating the Boost logo there. It's capitalized in the page title.
