### ISSUE TITLE
Discussion forums are still "coming soon" on the website

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2#999]
https://www.boost.io/community/

The Discussion Forums tile still says "coming soon", while the forum idea has been [cancelled](https://github.com/boostorg/website-v2/issues/965#issuecomment-1947332947).

**Comment by vinniefalco** [comment]
We have a plan for a different thing which looks like a forum but is really the mailing list. That is "coming soon."

**Comment by rbbeeston** [comment]
This was changed at some point to specify that it's the mailing lists, so there is nothing more to be done with this until some kind of forums are added
